### ISSUE TITLE
Major bug: Magnetic Coordinate Plotting

### ISSUE THREAD

**Issue by w2naf** [vtsuperdarn/davitpy#101]
Hi, guys.

I started making a new notebook to demonstrate basic SuperDARN data plotting (branch: feature_plotting_notebook), especially in response to request from Judy Stephenson.  I especially ran into trouble when trying to plot fan plots in magnetic coordinates:

```
pydarn.plotting.fan.plotFan(datetime.datetime(2013,3,16,16,30),['fhe','fhw'],param='power',gsct=False)
```

![index](https://cloud.githubusercontent.com/assets/1831182/4315196/3c382560-3ef0-11e4-8cef-7d58eaadae81.png)

```
pydarn.plotting.fan.plotFan(datetime.datetime(2013,3,16,16,30),['fhe','fhw'],param='power',gsct=False,coords='mag')
```

![index2](https://cloud.githubusercontent.com/assets/1831182/4315225/e7be8c4e-3ef0-11e4-80d8-1d23b8951f99.png)

Is anyone else familiar with this problem?

Thanks,
Nathaniel

**Comment by asreimer** [comment]
This bug still exists.

**Comment by ksterne** [comment]
Closing this down as seems as though we never got around to fixing things and this repo has now lost support.
