### ISSUE TITLE
MLT plotting labelled with degrees, not MLT

### ISSUE THREAD

**Issue by mrwessel** [vtsuperdarn/davitpy#102]
Maps plotted in MLT end up showing degrees from magnetic local midnight, not actual MLT.

**Comment by ksterne** [comment]
I think we're good to close this old, old bug?

**Comment by asreimer** [comment]
I don't know. I just tried making a convection map using my old testing code in #103 and the mlt labels are wrong.

**Comment by aburrell** [comment]
Same here.  I think this is a problem that was never addressed.

**Comment by asreimer** [comment]
While I don't remember explicitly and haven't looked through the commit history to verify, I merged #103 because it did fix the labeling issue. Something else maybe broke it?

Either way, it appears this MLT labeling issue still persists...

**Comment by mrwessel** [comment]
Testing with python plotUtils.py produces the desired result for me.  Others please verify.

**Comment by asreimer** [comment]
This is fixed in #102.
