### ISSUE TITLE
Add  a find_nearest method to *DataTypes

### ISSUE THREAD

**Issue by mrwessel** [vtsuperdarn/davitpy#106]
This method in radDataTypes/sdDataTypes would take a datetime (or possibly a range of datetimes) as input, then find the item(s) in the record index with the closest datetime key(s).  This is especially useful because the keys often include milliseconds, making them (typo-prone) work to enter by hand and difficult to specify automatically...without using code to find the nearest to a given datetime, that is.  This method would simply make that built-in.

**Comment by ksterne** [comment]
Certainly would have been an awesome feature.  Sorry we never got around to it.  Closing now for deprecation.
