### ISSUE TITLE
Notebook to explain all davitpy data types and how/where they're used

### ISSUE THREAD

**Issue by cmeeren** [vtsuperdarn/davitpy#113]
I'm pretty much in the dark when it comes to most of the data types/structures we're using. It seems to me I that if I want to know the data types we use, I would need to go digging in the source code, play around with different data types, explore their attributes and methods, and find out where and how they are used (e.g. which functions and methods accept which of the datatypes).

I think it would be a good idea to make a notebook which goes through all the different data types/structures we use, and explains how they're structured and how and where they're used, including how they can be of use to the user (e.g. getting data for a time interval and passing that data structure when looping over the time interval to do some plotting, just to name one example).

**Comment by ksterne** [comment]
Agree this was a great idea.  Sorry it never came to fruition.  Closing this issue for now since this repository is being deprecated.
