### ISSUE TITLE
davitpyrc

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#115]
As stated by the wise @jspaleta, chapter vtsuperdarn/davitpy repository, verse https://github.com/vtsuperdarn/davitpy/issues/56 "we need to move to a pydarnrc file that has all the user configurable environment stuff instead of all the environment shell variables. A real config file for all of pydarn environment configurables will fully solve the problem. Like how the matplotlibrc works. And we need to make use of the XDG environment variables and drop or files into the directories defined via XDG like any other application that needs tmp files or config files and data files. Basically we need to stop re-inventing the wheel. I say that with full knowledge that I've invented several of the oddly shaped wheels in the codebase." Seriously though, this is a very good idea and we need to start working on this.

We have a bunch of environment variables that are used by `radDataTypes` and `sdDataTypes` and a honestly, the way it is set up is really ugly and messy. A configuration file that handles this would be much cleaner. Also, we have a need for a configuration dictionary for initializing the logging library as discussed in https://github.com/vtsuperdarn/davitpy/pull/109. As we keep developing, I think we will only see an increased demand for an rc file.

So let's get working on that. To get the conversation started what is an "rc file"? "rc" is short for "Run command" and you can read more about it here: http://en.wikipedia.org/wiki/Run_commands This might also be interesting and is certainly relevant: http://en.wikipedia.org/wiki/Configuration_file

How would it "look" if we were to implement a davitpyrc file? For an idea, we can study matplotlib. When we run `from matplotlib import pyplot`, the `pyplot.py` file runs an `import matplotlib`, which in turn executes `__init__.py` here: https://github.com/matplotlib/matplotlib/tree/master/lib/matplotlib

In the `__init__.py` file, there is a call to `import matplotlib.rcsetup` (see this line: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L197).

So one potential way to package davitpy is to model it after matplotlib. The basic idea would be to have a root level `__init__.py` in the davitpy directory which is in turn imported by every davitpy module (pydarn, models, etc.). Then an `rcsetup.py` file can be placed in the davitpy directory that handles reading a `.davitpyrc` configuration file and has hardcoded defaults to fall back to. 

Here is the matplotlib `rcsetup.py` for reference: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/rcsetup.py. Of specific interest to us right now is probably the `defaultParams` dictionary found here https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/rcsetup.py#L479

Here's some more useful information about matplotlibrc: http://matplotlib.org/users/customizing.html

Here's where/how the rcParams dictionary is populated: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L1079 and https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L923 and https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L833

So, let's have a conversation and figure this out. What's the best way to proceed? Do we need to reorganize the way davitpy is currently packaged? Is davitpy supposed to function as a software library, or a framework (with pydarn, models, etc. as libraries)?

**Comment by asreimer** [comment]
I've started working on this. ETA end of January.

**Comment by asreimer** [comment]
I've refactored the code so it is ready for the rc_params dictionary to be added. The branch that I'm working in is here: https://github.com/asreimer/davitpy_asr/tree/enhancement_rc_params

The biggest change that has been made is that the `pydarn`, `models`, `gme`, and `utils` libraries have all been moved in to a `davitpy` directory. Also, instead of using `import x` to get at `pydarn`, `models`, `gme`, and `utils`, you now need to use `from davitpy import x`. This is similar to how `matplotlib` is packaged and I think it is a much cleaner and clobber/shadow proof way to package a python library.

If anyone has any feedback on what I've done so far, I would greatly appreciate it.

**Comment by cmeeren** [comment]
+1 for everything being inside `davitpy`!

**Comment by w2naf** [comment]
I support this, too!

~Nathaniel

**Comment by asreimer** [comment]
Enhancement added by https://github.com/vtsuperdarn/davitpy/pull/141
