### ISSUE TITLE
fetchUtils fails to find convection map files for some directory structures

### ISSUE THREAD

**Issue by mrwessel** [vtsuperdarn/davitpy#118]
If I have a directory structure with no time keys in it, e.g., `/home/matt/mapfiles/`, fetchUtils will not find files there because of the way time key searching (lines 203 to 231 in develop) is set up.  An `ls` is only run on the directory if a time key is found in the directory format.  If the directory format is being set manually anything should be possible, and if for some reason that isn't allowed a check needs to be added because the current situation produces a somewhat cryptic error.

**Comment by ksterne** [comment]
That was certainly not well tested for directories that do no have a time key.  However, this issue is being closed now as the repo is being deprecated.  Apologies it was never resolved.
