### ISSUE TITLE
Iterative data reading or memory leak

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/davitpy#119]
Moving this off of the google group and into github since it seemed as though it was a problem with the code and not something that I was doing.  

Again, here is a summary of the problem I'm seeing:

I'm running some code that reads in rawacf files for an entire day for one radar, searches for certain characteristics and then moves on to the next day in repeat. I'm doing a radDataOpen for each day.  However, after about a month and half or maybe two months of doing this, the code crashes as something seems to fall apart in the copying of data to the local machine as well as the concatenation.

The very basic of what I'm trying to run can be found in my github repository at:
https://raw.githubusercontent.com/ksterne/radops/master/acfd_find.py

**Comment by ksterne** [comment]
This was bad programming on my part as you see from the example code that I open the myPtr, but never close it.  Added a myPtr.close() to the end and I think it's working much better.

**Comment by asreimer** [comment]
Good to know! Thanks!
