### ISSUE TITLE
A bug in plotUtils.py

### ISSUE THREAD

**Issue by Shirling-VT** [vtsuperdarn/davitpy#126]
When I ran the maps.ipynb in the notebook, the following error came out:
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-5-e40ba87ab2a6> in <module>()
      2 # Plot map
      3 subplot(121)
----> 4 m1 = plotUtils.mapObj(boundinglat=30., gridLabels=False)
      5 overlayRadar(m1, fontSize=8, all=True, markerSize=5)
      6 subplot(122)

/usr/local/lib/python2.7/dist-packages/davitpy-0.2-py2.7-linux-x86_64.egg/utils/plotUtils.pyc in __init__(self, datetime, coords, projection, resolution, dateTime, lat_0, lon_0, boundinglat, width, height, draw, fillContinents, fillOceans, fillLakes, coastLineWidth, coastLineColor, grid, gridLabels, showCoords, **kwargs)
    137 
    138     if draw:
--> 139       self.draw()
    140 
    141   def draw(self):

/usr/local/lib/python2.7/dist-packages/davitpy-0.2-py2.7-linux-x86_64.egg/utils/plotUtils.pyc in draw(self)
    183           merLabels = [False,False,False,False]
    184         # draw meridians
--> 185         out = self.drawmeridians(meridians, labels=merLabels, fmt=lonfmt,
    186                                  color='.6', zorder=10)
    187 

UnboundLocalError: local variable 'lonfmt' referenced before assignment

It turns out that the parameter "lonfmt" isn't assigned when gridLavels=False. I add two statements (indicated by "# added by shirling" ) to the function "def draw(self):" inside "plotUtils.py" to fix this bug, as is shown below:

        # label meridians on bottom and left
        if self.coords == "mlt":
          meridians = np.arange(0.,360.,15.)
          lonfmt = lambda x: "%02g"%(x*24./360.)                # added by shirling 
        else:
          meridians = np.arange(-180.,181.,20.)
          lonfmt = "%g"                                                         # added by shirling 
        if self._gridLabels: 
          if self.coords == "mlt":
            merLabels = [True, False, False, True]
          else:
            merLabels = [False,False,False,True]  
        else: 
          merLabels = [False,False,False,False]
        # draw meridians            
        out = self.drawmeridians(meridians, labels=merLabels, fmt=lonfmt,
                                 color='.6', zorder=10)

It seems work after the revision, can anyone test it and do something, cause I'm still new to Git and Github.

**Comment by asreimer** [comment]
Thanks for the report @Shirling-VT! Could you let me know what branch you were using when you encountered this bug? We have different procedures for fixing bugs depending on if they occur in the `master` or the `develop` branch.

**Comment by Shirling-VT** [comment]
It is the develop branch. Thanks for your reply~

**Comment by asreimer** [comment]
Fixed in https://github.com/vtsuperdarn/davitpy/pull/127.

**Comment by Shirling-VT** [comment]
Thanks, Aston! I'm sorry I just merged them accidentally, but test them afterward. It works well. Please let   me know if I did something wrong.

**Comment by asreimer** [comment]
#127 has been merged, issue resolved.
