### ISSUE TITLE
Ensure davitpy figures are backend agnostic.

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#128]
Have a look at the `rti.py` and `fan.py` codes and see that they support plotting to a file. This is great functionality to have. As @sdelarquier has mentioned in the past, it is particularly useful if one wants to run davitpy on a server through an ssh connection without a GUI. This means that we should work towards a codebase where all plotting routines can easily plot to files. It would be very nice if we didn't have to repeat the same code over and over again in each of the plotting files. So here's what we need in summary:

1) Functionality that allows the user to easily plot to GUI or to a file
2) Generalized code to make development much easier.

The solution to this as I (currently) see it is to make a very simple generalized figure class. Something that can be called in a manner as easily as `fig = davitpy.figure()` that handles the file/GUI plotting stuff in the background based on `davitpyrc` settings. Since these settings will be configurable on the fly, this means that a user can very easily change whether they want to plot to a file or GUI by changing the `davitpyrc` dictionary.

Maybe we don't actually need this though. Anyone know/think of a better/easier/simpler solution?

**Comment by aburrell** [comment]
Hmmm…  I wonder if it wouldn’t be better to make a module (plotUtils.py, perhaps) and include these as functions since we don’t have any data to hold.  It could hold a lot of things that are done to create figures, like outputting the file/gui, adding a colorbar, creating a title string based on radar code and time (for example), et cetera.

**Comment by asreimer** [comment]
So investigating this, I don't think making a generalized figure class is a good idea. Doing this is a bit complicated and also may result in davitpyrc settings that clobber settings in matplotlibrc. Instead, we should make sure that our code is backend agnostic and that by default it returns the figure object for any figures being made so that the user can decide to save the figure manually or let their matplotlibrc settings handle things.

**Comment by aburrell** [comment]
This course of actions sounds best to me.

**Comment by asreimer** [comment]
With pull request #149 RTI plotting has been made backend agnostic.
