### ISSUE TITLE
Redundant cached file checking in rad/sdDataOpen

### ISSUE THREAD

**Issue by mrwessel** [vtsuperdarn/davitpy#130]
fetchUtils already checks for for cached files so it's no longer necessary for rad/sdDataOpen to do the check.

**Comment by asreimer** [comment]
The redundant file cache checking has been removed in #249. It relies solely on fetchUtils file cache checking instead.

**Comment by ksterne** [comment]
Looks like this was resolved but never closed.  Closing it now as the repo is being deprecated.
