### ISSUE TITLE
Handling/removal of unneccesary environment variables

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#135]
As I've been switching the codebase over to using entries in a `rcParams` dictionary (see https://github.com/vtsuperdarn/davitpy/issues/115) instead of environment variables, I've encountered a few that I'm not sure what to do with. Specifically, `DBWRITEUSER` and `DBWRITEPASS`. I don't know what they are supposed to be set to, and I don't know the consequences of default values being available on the internet. For example, with our file fetching from the VT data server, users have read-only access, whereas with `DBWRITEUSER` and `DBWRITEPASS`, it looks like they provide write access to a database.

Is it fine to have these in the `rcParams` dictionary with a default value set to nothing? It would be ideal if we didn't have to set any environment variables at all.

**Comment by aburrell** [comment]
Keeping them empty sounds good to me.  I wonder, though, if there’s a bit we could add to the setup that fills these values for each user upon installation?

**Comment by w2naf** [comment]
Hi, everyone.

I would say unless we are absolutely sure they are no longer in use, we keep them in.  Things we want to get rid, but aren’t sure about, we can comment out for now.

I do know about DBWRITEUSER and DBWRITEPASS.  Those are used by the routines that populate the MongoDB databases.  Virginia Tech may be the only one that uses those right now, but they could be used by anyone who sets up their own mongo sever.  Right now, I’m aware of the MongoDB doing 3 different things:

1. Serving GME (OMNI, AE, SYM-H, etc.)
2. Providing hdw.dat information (unless you have configured your system to use local hdw.dat files)
3. Alternative access to radar data (Not really in use now, and I don’t really see this going anywhere in the future).

~Nathaniel

**Comment by asreimer** [comment]
Thanks for the feedback! I'll definitely keep them around, but I will set them as empty by default. 

What I will do is include them in the `davitpyrc.template` (https://github.com/asreimer/davitpy_asr/blob/enhancement_rc_params/davitpyrc.template) and I'll add them to the `defaultParams` (https://github.com/asreimer/davitpy_asr/blob/enhancement_rc_params/davitpy/rcsetup.py#L182) dictionary where they will be an empty string by default.
