### ISSUE TITLE
Incorporate remaining environment variables into rc_params

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#136]
So I've finally finished the rcParams stuff, but in the interest of progress, I wasn't able to replace all references to environment variables with `rcParams` dictionary entries. Here is a list of files that still contain `os.environ` calls or references to environment variables:

* aacgm.c
* radStruct.py
* radInfoIo.py
* pydarn/radar/`__init__.py`

I may have neglected some files in the models directory. The environment variable in aacgm is particularly interesting to deal with. I have added some code to the `setup.py` for davitpy that copies the aacgm tables into the install location with the rest of the code, so now we just need to figure out how to get the `aacgm.c` code to point towards where the tables are installed. The idea here is that I should be able to download the davitpy source, compile and install it, and then delete the source files and directory and davitpy should still work. Is this the way we want things?

**Comment by w2naf** [comment]
Hi, @asreimer!

I pulled your changes and pushed them to my branch/pull request.  I'm now testing the notebooks to check for problems.  Currently, the following work on my machine (with 1 bug fix, included here):

*GOES.ipynb
*MUSIC-Simulate.ipynb
*MUSIC.ipynb
*SuperDARN Data Plotting.ipynb
*maps.ipynb

The following have issues:
*geoPack.ipynb
*models.ipynb

I haven't tested anything else yet.

So far, I've been testing on a machine I've been using for a while.  However, I'm going to create a clean virtual machine and continue my testing from there.  I'll try my best to fix bugs.  I also welcome anyone else who wants to test.

Cheers,
Nathaniel

**Comment by asreimer** [comment]
Fixed by https://github.com/vtsuperdarn/davitpy/pull/141
