### ISSUE TITLE
Complete uninstallation?

### ISSUE THREAD

**Issue by johncoxon** [vtsuperdarn/davitpy#140]
I'm using Anaconda and MacPorts. I installed davitpy but I haven't really been using it – the only thing I wanted was the Tsyganenko model, which I believe is still not working in the latest release. If I use `port` and `pip` to uninstall the packages installed by setup.py and delete the davitpy folder on my machine, will that zap everything that davitpy installed? Or are there things that are lurking elsewhere which won't be caught by doing this?

**Comment by aburrell** [comment]
It should.  You just need to check your python library folder to be sure.
