### ISSUE TITLE
radar/radInfoIo bugfix in master branch

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/davitpy#142]
I was looking into something today and noticed that on the master branch the radInfoIo file has a bug in it where the hdwRead function has a reference to a sys function, but sys isn't imported as it is in the other functions.  It looks like Nathaniel reworked this for the develop branch, but can I just add the import sys to that for the master branch to fix that?

**Comment by asreimer** [comment]
If we want to follow our branch and pull model, create a branch from master called `hotfix_radInfoIo_sys_bug` and then make the change there and make a pull request. I'm guilty of not following this one time in the past.

**Comment by asreimer** [comment]
I can merge the pull request as soon as you post it.

**Comment by ksterne** [comment]
Done it with #143.  Thanks for the refresher on the proper way to do this.

**Comment by asreimer** [comment]
Yup, merged it.
