### ISSUE TITLE
davitpy breaks IPython upon installation

### ISSUE THREAD

**Issue by johncoxon** [vtsuperdarn/davitpy#146]
I'm running Anaconda 2.3.0 with Python 2.7.10 on OS X 10.10.5. I installed davitpy today, using the following steps. Firstly, I cloned the repo using GitHub's OS X app and cloned my root environment in Anaconda to an environment called `davitpy`. Then, I did:    

    sudo ./install/python_install_mac_port.sh

It should be noted that the call to `./mastermake` at the end failed, presumably because it's in a different directory to the install script? Upon this finishing, I opened a new Terminal window. I got an error from bash that my profile couldn't find the file `profile.mac` so I manually edited the line to the correct path to that file, and then opened a second new Terminal window and ran

    source activate davitpy
    ./mastermake

Once this had completed, I attempted to run IPython in a new Terminal window outside the `davitpy` environment, which resulted in the following:

    Traceback (most recent call last):
      File "/Users/jc3e14/anaconda/bin/ipython", line 4, in <module>
          from IPython import start_ipython
      File "/Users/jc3e14/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 47, in <module>
          from .core.application import Application
      File "/Users/jc3e14/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 22, in <module>
          from traitlets.config.application import Application, catch_config_error
      ImportError: No module named traitlets.config.application

I'm not sure I can be of much more help, since I've nuked `~/anaconda` and am currently reinstalling it, but I thought it might be helpful to post this up. I'm sure it's connected to the davitpy installation since I haven't installed or removed any other Python packages in the recent past.

**Comment by asreimer** [comment]
Once you get anaconda reinstalled, can you let us know if ipython is working or not? @w2naf recently found out that ipython and the ipython notebooks have been going through substantial changes: 
in #144 @w2naf wrote:
>
>Hi again, @asreimer . So it turns out that iPython, the notebook, and other modules that were part of >iPython are splitting (http://blog.jupyter.org/2015/04/15/the-big-split/). I'm finding out that this means that >once you update a system and re-run our dependencies script, the notebooks don't work.
>
>Unfortunately, they don't yet have it set up so you can simply run "pip install notebook". They say it is >coming. In the mean time, I'm trying to figure out how to get notebooks to run on my machine again.
>
>We will also need to know how to make our install scripts work in this situation.
>
>~Nathaniel

Also, I'm not sure how good the mac install scripts are. We've had some problems with them in the past (a la: #122) and I don't have a mac to do any testing on (not part of the cool-kids club or whatever /s). @GPerry306 recently let me know that he was able to get davitpy install on OS X Yosemite, but he didn't use Anaconda.

**Comment by johncoxon** [comment]
It worked upon reinstall, yup.

**Comment by asreimer** [comment]
Probably this line: https://github.com/vtsuperdarn/davitpy/blob/master/install/python_install_mac_port.sh#L19

is overwriting the installation of ipython that anaconda installs. This combined with the changes they are making to ipython is probably causing you problem, but without a mac myself, I can't help you out much more than that. 

You could try using the install script (`python_install_mac_port.sh`) as a guideline for what you need to have installed rather than running it outright.
