### ISSUE TITLE
davitpy-notebook command fails after install

### ISSUE THREAD

**Issue by jaestephenson** [vtsuperdarn/davitpy#147]
Please help me with an issue I am having with DavitPy installation. I am starting a new install of it on a Ubuntu 14.04 machine. Using Python 2.7.6. I def am in a bash shell. I notice a difference from my last install (last year) using develop branch. I could not get this to work, so instead used the setup branch as indicated on the website. All went will with the installation but when I type "davitpy-notebook" to get the notebooks up in iPython I get error and the web browser does not open. I have copied below a detail of the error meassages when I type this command.
 File "<string>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/lib/python2.7/dist-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named notebook.notebookapp
zmtumela@zmtumela-OptiPlex-9020:~/davitpy/docs/notebook$ davitpy-notebook > notebookerror
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/lib/python2.7/dist-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named notebook.notebookapp

**Comment by MuhammadVT** [comment]
Hi,

Please take a look at the issue #146
<https://github.com/vtsuperdarn/davitpy/issues/146> which might be relevant
to you.

Thank you

**Comment by asreimer** [comment]
Hey @jaestephenson 

What did you do to install the current development branch? For example, it is a bit harder to know what could be causing the problem without knowing whether or not you re-ran the debian_dependencies.sh script in the install directory. Can you tell us what you did to install davitpy?

I suspect the problem you are having is related to the new changes to ipython and ipython notebooks (which is why @MuhammadVT referred you to #146, where another person also had trouble with ipython, although you aren't on OSX so it won't necessarily be relevant).

**Comment by garimamalhotra** [comment]
Hi,

I have faced the same issue and I solved it by removing and then freshly
doing a pip install on ipython notebook.

On Tue, Sep 15, 2015 at 2:47 PM, asreimer <notifications@github.com> wrote:

> Hey @jaestephenson <https://github.com/jaestephenson>
>
> What did you do to install the current development branch? For example, it
> is a bit harder to know what could be causing the problem without knowing
> whether or not you re-ran the debian_dependencies.sh script in the install
> directory. Can you tell us what you did to install davitpy?
>
> I suspect the problem you are having is related to the new changes to
> ipython and ipython notebooks (which is why @MuhammadVT
> <https://github.com/MuhammadVT> referred you to #146
> <https://github.com/vtsuperdarn/davitpy/issues/146>, where another person
> also had trouble with ipython, although you aren't on OSX so it won't
> necessarily be relevant).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vtsuperdarn/davitpy/issues/147#issuecomment-140496101>
> .
>



-- 
Regards

*Garima Malhotra*
*Virginia Tech*
*Ph :+1540-750-6057*

**Comment by jaestephenson** [comment]
Hey Ashton

I don't know if you remember me but I was at SD in Leicester?

I would be very grateful with your help with DavitPY installation as the
instructions seem confusing!.

In my install attempt I used the develop branch and then installed the
dependencies. The makefile would not compile anything and I noticed that
the .bashrc had not been modified. So then I tried to checkout the setup
branch and re-installed dependencies, then the makefile worked then I did
the DavitPY install with "sudo python setup.py install" and did makefile
again. Then logout and then when I tried the command "davitpy-notebook" I
got the errors I listed above. I hope this is clear. I obviously now have
to do a re-install? Please can you give me unambiguous instructions how I
can achieve this?

Kind regards

Judy

**Comment by asreimer** [comment]
Hi Judy,

I do remember seeing you in Leicester! Although I'm not sure if we had the chance to be properly introduced. 

As you and @ksterne have pointed out the instructions in our current README are not up to date. Sorry about that. I'll try to give you some clear installation instructions here. I'll start from the very beginning assuming you have never installed davitpy before. I'm also going to assume that you want to use the `develop` branch (has the latest features, isn't really buggy):

**Remove the old DaViT-py installation (optional)**
1) Execute `pip uninstall davitpy`
2) Remove any davitpy entries in your .bashrc file.

**Getting DaViT-py and switching to the develop branch**
1) Ensure the you have `git` installed on your computer.
2) Clone the davitpy repository with `git clone https://github.com/vtsuperdarn/davitpy.git`
3) You should now have a `davitpy` directory, so change into it with `cd davitpy`
4) Run the command `git branch` to see the current branch that you are on. It should be `master`
5) Pull down the develop branch with `git fetch origin develop:develop`
6) Switch to the develop branch with `git checkout develop`

**Installing DaViT-py**
1) To ensure that you have all the required dependencies needed to run davitpy, navigate to the `install` directory in the davitpy repository and run the appropriate script (if you are on ubuntu use the debian script)
2) Once this script has completed then you can run the setup.py file in the main directory of the repository. To do this simply use the command `python setup.py install --user`. If you don't include the `--user` switch then DaViT-py will be installed system-wide.

**Setting up davitpy and/or davitpy-notebook executables**
1) Navigate to the `bin` directory and read the README there.

Hopefully these instructions help you out!

A brief summary of changes for you: In the develop branch we have removed the need for environment variables to be set for davitpy to work so nothing will be added to your .bashrc file anymore. Davitpy is also now installed as one package. So to get at pydarn for example, you now do:
`from davitpy import pydarn`

Things are still a bit rough around the edges but it should all install and work fine. Ideally, we would like davitpy to be installed with a single `pip` command but first we need to get to a 1.0 release stage. If you are interested in helping with development let us know!

**Comment by asreimer** [comment]
I should mention that we no longer support the davitpy-notebook command. If you want that, simply add an alias to your shell environment. In bash, something like:

`alias davitpy-notebook='ipython notebook` 

should do it. Consult the README in the bin folder for the `davitpy` command.

**Comment by jaestephenson** [comment]
Awesome. Thanks Ashton :) Will let you know how we get on

**Comment by ksterne** [comment]
@jaestephenson, were things resolved here?  I'm wondering if we can close this issue even though it seems like this is like other issues ( #156, #146).

**Comment by MuhammadVT** [comment]
I think we can close it as Nathaniel's pull request (#157
<https://github.com/vtsuperdarn/davitpy/pull/157>) fixes the problem.

**Comment by w2naf** [comment]
I was just about to say that!!

**Comment by w2naf** [comment]
#157 is a pull request into develop, and #158 is the same thing into release-1.0.

**Comment by jaestephenson** [comment]
Hi

No DavitPy is not yet working. Zolile's enquiry follows problems after the
help I got from my issue.

Judy

**Comment by w2naf** [comment]
Hi, Judy.

Did you try this?
sudo pip install jupyter

Then, use the command “ipython notebook” instead of “davitpy-notebook”.  I think it will work.

The people who write iPython have recently split ipython and the notebooks into separate projects, and this has changed the software packages he need to install.

Take care,
Nathaniel

**Comment by jaestephenson** [comment]
Thanks Nathaniel. The problem is now resolved :)

**Comment by w2naf** [comment]
Great, Judy!  I'm glad it worked!

Nathaniel

**Comment by salsrag** [comment]
Nathaniel,

 

I had the opposite problem of Judy’s.  I believe that last night when I started working I had to use “ipython notebook”. However, I crashed my python this morning and when I restarted I had to use “davitpy-notebook”. Do I have two different  systems running on my machine and I have to be careful as to how I get to the notebook directory?

 

Ray
