### ISSUE TITLE
README / install instructions updates

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/davitpy#148]
As mentioned in https://github.com/vtsuperdarn/davitpy/pull/141 , the README file still mentions that the dependencies script will modify the ~/.bashrc file.  However, this doesn't seem to be the case after the merge from the above mentioned pull request.  Seems as though this needs to be edited as it may be confusing.

**Comment by ksterne** [comment]
Need to specify which branch should be used and how to switch between branches.  This may make a branch specific README file, but default when you clone davitpy is to be on the master branch.  This got me a number of times when I was trying to install code on something not the master branch.

**Comment by asreimer** [comment]
This is a good point. And we've been seeing some other people filing issues to do with installing davitpy so we should try to make this a higher priority.

**Comment by ksterne** [comment]
I addressed at least the reminder to switch branches with  b73fc6d6051a2007909dd1588e790182f3f59ace on the develop branch.

**Comment by ksterne** [comment]
I think this has been address by the change to using the davitpyrc file.  I just did a fresh install and I don't see anything being added or modified to the ~/.bashrc file or ~/.profile files.  At least on Ubuntu 16.

So I think to satisfy my issue over 2 years ago, we just need to remove the line in the README.md file that starts:
`Note that this script also modifies your ~/.bashrc file...`

Sound good here?  I'll get a PR into develop going.  Certainly closing and opening the terminal doesn't hurt, but it's an unnecessary step it seems.

**Comment by ksterne** [comment]
So, this issue should be satisfied by #343.
