### ISSUE TITLE
Possible bug in MLT (AACGM) calculation

### ISSUE THREAD

**Issue by tkanmae** [vtsuperdarn/davitpy#155]
I'm filing a possible bug in `astmlt()` in models/aacgm.

The function computes the solar apparent time `at`, which is a double, and passes it to `astmlt1()` as `t0`, which is an int. It seems that the implicit downcast produces a corrupted value for `t0`. For example, I got `t0 = 2.20979e-314` for `at = -347.008`.

**Comment by MuhammadVT** [comment]
Hi Takeshi,

Thank you for reporting the bug for us. We will address this issue.
As double *at  is *usually a large number, passing it to int *t0  *may only
have a very negligible effect in terms of precision.

Thanks

**Comment by tkanmae** [comment]
Muhammad,

I suspect that the implicit downcast introduces non-negligible errors in resultant magnetic local times.

`astmlt()` computes the solar apparent time `at` in units of seconds and declination `dec`in units of degrees, and passes them to `astmlt1()`. Note that `at` is passed to `astmlt1()` as a parameter `t0`, which is declared as an int. Using the solar apparent time, `astmlt1()` computes the sub-solar point in longitude (I guess this is what `(43200.0-t0)*15.0/3600.0)` does, given that 43200.0 is 12 * 3600.0.) and then computes the sub-colar point in geomagnetic coordinate in AACGM. Finally, `astmlt1()` computes the magnetic local time at a geomagnetic longitude of a point of interest.

If the above code analysis is correct, the variable `t0` in `astmlt1()` should correctly represents the solar apparent time in units of seconds. The corrupted value of `t0` produced by the implicit downcast likely introduces non-negiligible errors in the resultant magnetic local time. I would propose 

1. that you declare `t0` as a double in `astmlt1()`, or
2. that you explicitly downcast `at` as an int in `astmlt()` and passes it to `astmlt1()`.


Thanks,

Takeshi

**Comment by MuhammadVT** [comment]
Hi Takeshi,

I agree with what you said. Declaring *t0* in *astmlt1()* as double seems a
better approach to me. Since you have discovered this bug, would you mind
sending a pull request from your github account to our "develop" branch in
vt davitpy repository? We would appreciate if you could include some test
code that prints out the calculated mlt values before and after fixing the
bug, and compares them with the mlt value that can be taken as reference.

Thank you

Muhammad

**Comment by MuhammadVT** [comment]
Hi Takeshi,

I forgot to mentioned that the "develop" branch in our davitpy repository
is the most up-to-date one. Please do the bug fixing based on the "develop"
branch.

Thank you

**Comment by tkanmae** [comment]
Muhammad,

I will PR on this issue within a week. Do you mean that you want me to include commits with printing out relevant information?

Takeshi

**Comment by MuhammadVT** [comment]
Yes, that is what I meant.

Thank you.

**Comment by ksterne** [comment]
Since this has staled, I'm guessing this was fixed in a PR or release at some point.  I'm closing the issue now for deprecating this repo.
