### ISSUE TITLE
davitpy installation and notebook issues

### ISSUE THREAD

**Issue by zmtumela** [vtsuperdarn/davitpy#156]
Hi all,  I am new in  davitpy installation,  I have experience many complications, following the new way of davitpy installation.
1. I think I managed to install it until executing davitpy.  To get at pydarn, I used from davitpy import pydarn;
I get the ff
zmtumela@zmtumela-OptiPlex-9020:~$ davitpy 

DaViT-Py Copyright (C) 2012 VT SuperDARN Lab 
This program comes with ABSOLUTELY NO WARRANTY; for details see LICENSE.txt. 
This is free software, and you are welcome to redistribute it 
under certain conditions; for details see LICENSE.txt 

Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information. 

IPython 4.0.0 -- An enhanced Interactive Python. 
?         -> Introduction and overview of IPython's features. 
%quickref -> Quick reference. 
help      -> Python's own help system. 
object?   -> Details about 'object', use 'object??' for extra details. 

IPython profile: davitpy 

[TerminalIPythonApp] Loading IPython extension: storemagic 
[TerminalIPythonApp] Running code in user namespace: %load_ext autoreload 
[TerminalIPythonApp] Running code in user namespace: %autoreload 2 
[TerminalIPythonApp] Running code in user namespace: from davitpy import pydarn 
Loaded davitpyrc file from DaViTpy installation directory. Path: /home/zmtumela/.local/lib/python2.7/site-packages/davitpy-0.2-py2.7-linux-x86_64.egg/davitpy 
[TerminalIPythonApp] Running code in user namespace: from davitpy import utils 
[TerminalIPythonApp] Running code in user namespace: from davitpy import models 
[TerminalIPythonApp] Running code in user namespace: from davitpy import gme 
[TerminalIPythonApp] Running code in user namespace: from datetime import * 

In [1]: from davitpy import pydarn 

In [2]: 
I do not know how to proceed from here?
 2. Hence the new installation does not support davitpy-notebook command. I went to bashrc to add "alias davitpy-notebook='ipython notebook'

Now trying to use davitpy notebooks
log out and log in (i did this many times) then typed /home/zmtumela/davitpy/docs/notebook/davitpy-notebook I found this
bash: /home/zmtumela/davitpy/docs/notebook/davitpy-notebook: No such file or directory
I tried to check davitpy-notebook file under notebook, the file is  not there.
I followed many conversations here in this group and also the help of jaestephenson. I am stuck now
I will appreciate any help and suggestion.  I am new in installing this software.

Many thanks
Zolile

**Comment by walkeradm** [comment]
Hi Zolile

I am replying directly to you. I had the same problems in re-installing 
davitpy and have fixed it. The point seems to be that the new davitpy 
installation breaks ipython in some way .

This is what I did:

1. Completely removed old ipython (I used synaptic package manager, 
selcted all the ipython files and checked "completely remove")

2. Reinstalled the latest stable version of ipython to work with python 
2.7 through:
pip install ipython

3. Then I installed the new version of notebook which uses jupyter:
pip install jupyter.

3. You now run notebook by:
(a) changing to davitpy notebook directory.
(b) open notebook with command: ipython notebook

Try that

Dave

**Comment by zmtumela** [comment]
Hi Prof.
Thank you so much!! I have tried this and I got davitpy-notebook filr under notebook directory.
But I am still experiencing some problems like 
zmtumela@zmtumela-OptiPlex-9020:~$ /home/zmtumela/davitpy/docs/notebook/davitpy-notebook
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/usr/local/lib/python2.7/dist-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named notebook.notebookapp

Probable I made some wrong installation somewhere, I will keep checking and trying,  Thanks again.

Zolile

**Comment by MuhammadVT** [comment]
Hi Zolile,



Would you mind telling us the steps that you took for installing davitpy?

**Comment by MuhammadVT** [comment]
Hi Zolile,

Sorry, I sent an unfinished email accidentally.

It looks like the problem is with the Ipython Notebook, not the davitpy
itself. The instructions given by Prof. Dave should fix the Ipython
problem.  However, If you want to see some examples of davitpy, there are
test codes in the end of some of the files. (e.g., fan.py in
davitpy/pydarn/plottings/). If you need specific examples, please let us
know.

Also, Would you mind telling us the steps that you took for installing
davitpy and Ipython?

Thank you,

Muhammad.

**Comment by zmtumela** [comment]
Dear Muhammad
Thanks!! I followed the following steps for new davitpy installation

Remove the old DaViT-py installation
1) Execute pip uninstall davitpy
2) Remove any davitpy entries in your .bashrc file.

Getting DaViT-py and switching to the develop branch
1) Ensure the you have git installed on your computer >>>sudo apt-get install git

2) Clone the davitpy repository with >>> sudo git clone https://github.com/vtsuperdarn/davitpy.git
3) You should now have a davitpy directory, so change into it with cd davitpy
4) Run the command git branch to see the current branch that you are on. It should be master
5) Pull down the develop branch with >>> git fetch origin develop:develop
6) Switch to the develop branch with >>> git checkout develop

Installing DaViT-py
1) To ensure that you have all the required dependencies needed to run davitpy, navigate to the install directory in the davitpy repository and run the appropriate script (if you are on ubuntu use the debian script) i.e. >>> sudo ./install/debian_dependencies.sh
2) Once this script has completed then you can run the setup.py file in the main directory of the repository. To do this simply use the command >>> python setup.py install --user. If you don't include the --user switch then DaViT-py will be installed system-wide.

Setting up davitpy and/or davitpy-notebook executables
1) Navigate to the bin directory and read the README there.

Hopefully these instructions help you out! (In the star lines)
*******************************************************************************
Ipython Profile and 'davitpy' Executable

This README.md should contain instructions on how to setup a custom ipython configuration to automagically import the davitpy library when starting an ipython session. It should also contain instructions on how to install a 'davitpy' executable file (bash script) if you wish to do so. If this README doesn't contain this information, make a pull request to add it!

Ipython Profiles
================

The following has only been tested in linux (but should work in OS X, because bash).

To install the davitpy ipython profile, one simply needs to copy the 'profile_davitpy' directory in the bin folder of the davitpy repository into the ipython configuration directory. For example on Ubuntu 14.04, the ipython configuration directory is located in the home directory. For example:

/home/ashtonsethreimer/.ipython
so for my example, one simply needs to copy the 'profile_davitpy' directory into the '/home/ashtonsethreimer/.ipython' directory. To use this profile when using ipython, one simply executes the following command:

ipython --profile=davitpy


'davitpy' Executable
====================

The following has only been tested in linux (but should work in OS X, because bash). Also, it is important to note that the executable requires that you have followed the steps detailed above in the Ipython Profiles section of this README.

To install the davitpy executable, you will need to copy the davitpy file from the bin directory in the davitpy repository to some place on your computer. For the purposes of these instructions, we'll install it to a bin directory in your home folder. On my machine the path is '/home/ashtonsethreimer/bin/'. Be sure to make check that the davitpy file is executable. I would do that with the following command:

chmod +x /home/ashtonsethreimer/bin/davitpy
Next you need to inform your shell that you would like it search the bin directory for executable files. In bash, we edit the .bashrc file in the home directory. In tcshell, we edit the .tcshrc file in the home directory. For bash, we need to add the following line to the end of the .bashrc file:

export PATH=$PATH:/path/to/davitpy/file/
For me:

export PATH=$PATH:/home/ashtonsethreimer/bin/
Once you have added this line to your shell config file (the .bashrc or .tcshrc or whatever you have) you can start a new shell to test if it worked. You should simply have to type: davitpy and hit enter.

Alternatively, one may instead create an alias in the .bashrc (or .tcshrc or...) file (probably the best method). To do this in bash, one simply needs to add the following line to the .bashrc:

alias davitpy='ipython --profile=davitpy'

**********************************************************************************

A brief summary of changes for you: In the develop branch we have removed the need for environment variables to be set for davitpy to work so nothing will be added to your .bashrc file anymore. Davitpy is also now installed as one package. So to get at pydarn for example, you now do:
from davitpy import pydarn

Things are still a bit rough around the edges but it should all install and work fine. Ideally, we would like davitpy to be installed with a single pip command but first we need to get to a 1.0 release stage. If you are interested in helping with development let us know!

I should mention that we no longer support the davitpy-notebook command. If you want that, simply add an alias to your shell environment. In bash, something like:

alias davitpy-notebook ='ipython notebook'

should do it. Consult the README in the bin folder for the davitpy command.

USING DAVITPY NOTEBOOKS
======================= 
(if you done the above alias and logged out and in again then type /homedir/davitpy/docs/notebook/davitpy-notebook to open notebooks in web browser.

So far I am still trying but not winning.
Many thanks
Zolile

**Comment by MuhammadVT** [comment]
Hi Zolile,

Sorry, I can't suggest you a better way than what you have already
mentioned. However, I have converted all the ipython notebooks we have in
the davitpy/docs/notebooks directory into html files. I have tried firefox
to open them and they all look good. Although they are static, it might be
useful for you to get familiar with davitpy. I failed to attach them here
although the size is ~9Mb after compressing. Would you leave your other
email address here?

Thank you,

Muhammad

**Comment by MuhammadVT** [comment]
Hi Zolile,

One of our developers has just created a branch called
*hotfix_install_jupyter* in our davitpy VT repository , Please install this
branch and try Ipython Notebook. The installation is the same as you have
did before except that change *develop* branch into hotfix_install_jupyter.
By doing this, you are also giving us a big by testing this branch.

Thank you.

Muhammad

**Comment by zmtumela** [comment]
Dear Muhammad
Thank you so much. I will try that and i will let u know. My email address:zolilemtumela@gmail.com.
Many thanks
Zolile

**Comment by zmtumela** [comment]
Dear All,
Final, davitpy installation has been completed the davity-notebook is working. 
The hotfix_install_jupyter is working and helpful. Thank you all with all your help.
Many thanks
Zolile

**Comment by MuhammadVT** [comment]
Great. Thank you for helping us bring up the issue and testing the new
branch.
