### ISSUE TITLE
Plotting: Parameter Labelling

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#173]
Hey everyone,

Prompted by https://github.com/vtsuperdarn/davitpy/pull/151#issuecomment-150005370 and https://github.com/vtsuperdarn/davitpy/pull/124#issuecomment-68890436 we need to figure out what we want to do in regards to parameter labelling in our plotting routines. For example, should we label velocity with "m/s", or "$m s^{-1}$", or "$\frac{m}{s}"? Do all journals have similar/same labelling/styling requirements? This discussion should of course include font selection and font sizes, etc.

So let's discuss this and figure out exactly what we want to do. 

One solution to this problem is to implement a "paramLabel" dictionary in the `davitpy/rcsetup.py` file that contains dictionaries of all the parameter labels. Then the default labelling style can be selected by the user by setting a rcParams key. The rcParams key can then be overruled by an optional argument in the plotting routines.

**Comment by aburrell** [comment]
Font size selection can be made as a routine call.  I have a local routine I use to do this and I think it’s nice because you don’t always want the same font size for plots.

From what I’ve seen Annales and JASTP have the same requirements as JGR or have no problem if you follow the JGR requirements.  What other journals are people publishing in?

**Comment by salsrag** [comment]
The most important issue is font size. In the end it has to be legible.  Font sizes for presentations are not necessarily the same as font sizes for publications, especially if one has to reduce the figure to 1 column in a 2 column spread. A related issue is having too many axis labels. What may look good for a presentation in landscape format, will look very crowded when reduced to a single column with increased font size. It would be nice if we could identify the intended use and have and have the plotting package automatically choose the proper scaling, etc.
