### ISSUE TITLE
`spacepy` dependence in `timeUtils.py`

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#188]
While refactoring timeUtils code (#187), I noticed that the `julToDatetime` method depends on `spacepy`, yet none of the dependency scripts include installing `spacepy`. At the very least we need to add `spacepy` installation in the dependency scripts. But, I would recommend that we don't do this.

Currently, only 1 method in davitpy requires `spacepy`. What I propose is that we replace the `spacepy` call with code that replicates the functionality.

Unless there a dependency is used "extensively" in our codebase, I think we should strive to minimize the number of dependencies we have.

**Comment by aburrell** [comment]
I agree.  It’s generally bad form to require loads of dependencies in a package.  Also, spacepy can be very difficult to install.

**Comment by cmeeren** [comment]
Absolutely agree on this. There is a balance between reinventing the wheel and not having too many or too heavy dependencies, but in this case I think we should definitely write our own code.
