### ISSUE TITLE
Terminator plotting

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/davitpy#193]
Testing out the #185 pull requestion I was wondering if I had broken something at the end of the code in the daylight terminator plotting.  Seems as though something has fallen out of place or is wrong with it.  This is the code I used:

from davitpy.pydarn.plotting import plot_rti
from datetime import datetime,timedelta

import matplotlib.pyplot as plt

f = plt.figure()

stime = datetime(2014,7,10,0,0)
etime = datetime(2014,7,10,6,0)

fig = plot_rti(stime,'sas',params=['elevation'],coords='geo',bmnum=2,eTime=etime,fileType='fitacf',plot_terminator=True)

plt.show()

And this is the plot that I got:

![terminator_plot](https://cloud.githubusercontent.com/assets/3009489/11874895/e549b6ac-a4af-11e5-8c27-b9325b872504.png)

Maybe it's just something very simple with the opacity of the night plotting.  I'm not sure I ever saw this work in davitpy, but in other instances usually the "nighttime" area is more of a grey that is behind the radar data.

**Comment by asreimer** [comment]
Oh dear. Should be a simple fix though, something like setting the alpha and also setting the zorder (opacity and push the terminator to the background).

**Comment by asreimer** [comment]
Looking at this I redact my "should be a simple fix" comment. If you try to plot the terminator for the whole day, bad things happen to your computer.

**Comment by ksterne** [comment]
I found that kind of "bad things happen" as well.  I did seem something from about setting a mask to nan or something along those lines.

**Comment by asreimer** [comment]
Found it! It was all my fault (again). Here's the [relevant chunks of code](https://github.com/vtsuperdarn/davitpy/blob/develop/davitpy/pydarn/plotting/rti.py#L1106-L1109).

Notice how that chunk of code gets called on EVERY iteration of the for loop? That's not supposed to happen. I messed up the indentation there. It should be unindented once.

**Comment by asreimer** [comment]
I'll fix this in a new pull request...

**Comment by asreimer** [comment]
Pull request that fixes this issue here: https://github.com/vtsuperdarn/davitpy/pull/194
