### ISSUE TITLE
Add an upgrade pip command in debian_dependencies.sh?

### ISSUE THREAD

**Issue by Shirling-VT** [vtsuperdarn/davitpy#195]
Hi, everyone,

I was trying to installing the develop branch of davitpy yesterday and found that I could not use the notebook after I finished the installation. 

The error information shows like this:
ImportError: No module named functools32

    Jupyter notebook format depends on the jsonschema package:
    
        https://pypi.python.org/pypi/jsonschema
    
    Please install it first.

It seems that jsonschema is missing, but I did install  jsonschema package. Then I found out that it is because my pip is an old version, I need to upgrade it before installing jsonschema so that it will find the dependencies correctly. Therefore, I wonder if we should add a simple upgrade pip command inside debian_dependencies.sh to solve this issue?

**Comment by asreimer** [comment]
This is already in the `debian_dependencies.sh` [script](https://github.com/vtsuperdarn/davitpy/blob/master/install/debian_dependencies.sh#L33) and the `suse_dependencies.sh` [script](https://github.com/vtsuperdarn/davitpy/blob/master/install/suse_dependencies.sh#L54).

What were you running when you had this problem?

**Comment by Shirling-VT** [comment]
It has been a while ago when I tried to install davitpy in my old lab
computer. Since that old computer was dead, and the installation of pip is
working fine in my new computer, so I cannot repeat this error, it could be
something wrong with my computer. Thanks a lot for your reply, Ashton!

On Thu, May 5, 2016 at 2:18 PM, Ashton Reimer <notifications@github.com>
wrote:

> This is already in the debian_dependencies.sh script
> <https://github.com/vtsuperdarn/davitpy/blob/master/install/debian_dependencies.sh#L33>
> and the suse_dependencies.sh script
> <https://github.com/vtsuperdarn/davitpy/blob/master/install/suse_dependencies.sh#L54>
> .
>
> What were you running when you had this problem?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vtsuperdarn/davitpy/issues/195#issuecomment-217232122>
>



-- 
Best wishes,
Xueling
