### ISSUE TITLE
sqlInit() Error unable to open database file: /tmp/sd/.radars.sqlite

### ISSUE THREAD

**Issue by loisks317** [vtsuperdarn/davitpy#204]
When I run the ray tracing notebook, I get this error message:

sqlInit() Error unable to open database file: /tmp/sd/.radars.sqlite

I tried the #81 bug fix and I'm just not getting anywhere. I have the latest version of davitpy because I just downloaded it last week. When I looked at the __init__.py scripts in the pydarn/radar folder they are modified like the bug fix solution suggested. 

Any ideas?

**Comment by loisks317** [comment]
So I've more headway on this. What I get is: 
```
OperationalError                          Traceback (most recent call last)
/Users/loisks/Documents/ResearchProjects/SANSAProject/davitpyStuff/plotRays.py in <module>()
     10 rto = raydarn.RtRun(sTime, eTime, 
     11     rCode=radar, beam=beam, freq=freq,
---> 12     outDir='/tmp', nprocs=4)

/usr/local/lib/python2.7/site-packages/davitpy-0.4-py2.7-macosx-10.10-x86_64.egg/davitpy/models/raydarn/rt.py in __init__(self, sTime, eTime, rCode, radarObj, dTime, freq, beam, nhops, elev, azim, hmf2, nmf2, outDir, debug, fext, loadFrom, edens_file, nprocs)
     88 
     89             elif rCode:
---> 90                 self.radar = radar.radar(code=rCode)
     91 
     92             # Set azimuth

/usr/local/lib/python2.7/site-packages/davitpy-0.4-py2.7-macosx-10.10-x86_64.egg/davitpy/pydarn/radar/radStruct.py in __init__(self, code, radId)
    419                 with lite.connect(dbname) as conn:
    420                     cur = conn.cursor()
--> 421                     cur.execute('SELECT id,code FROM rad')
    422                     rows = cur.fetchall()
    423                 for row in rows:

OperationalError: no such table: rad
```

I think this might be a problem with finding the radar data. Any suggestions? I tried using my VPN, etc. but I'm not having any luck.

**Comment by ksterne** [comment]
Hello @loisks317,

This problem seems to keep coming up, or people have had problems with it in various ways.  I'm not as familiar with how things run for Mac, maybe @w2naf can speak more to this than I can.  If you are using the default configuration of setting DAVIT_TMPDIR to /tmp/sd/ in the davitpyrc file, then that is where the .radars.sqlite file should be located.  This file can be somewhat tricky to find since it has the hiding period on the beginning of it.  Maybe double check the value fir DAVIT_TMPDIR in the `davitpy/davitpy/davitpyrc` file.

Usually these issues have to do with the permissions of this file.  The .radars.sqlite should be owned by your users and have read/write access to it.  Can you confirm that the permissions are set this way?

**Comment by loisks317** [comment]
so the DAVIT_TMPDIR is set to be /tmp/sd in the davitpyrc file

You're right, the .radars.sqlite file only had read permissions! I changed that, but I am still having the same problems :(

**Comment by loisks317** [comment]
Also, when I open the .radars.sqlite file, there's nothing there. I'm not sure where in rt.py the file writes the radar information here. Why can't it read from a data file or webscrape?

**Comment by MuhammadVT** [comment]
Hi Lois,

I have reinstalled the develop branch of davitpy in our VT GitHub page, and
ran the raytracing code with no error message you have encountered. Just to
make sure it runs on a clean system, I have installed davitpy on a virtual
machine with a clean ubuntu14.04. Again, it is running well. So, as Kevin
has suggested, it looks like the problem is something local in your
machine. I would recommend you to install davitpy on a Oracle VM VirtualBox
<https://www.virtualbox.org/wiki/Downloads>  with ubuntu14.04 system. If
you have any problem after that please let us know.

Best Regards,

Muhammad

**Comment by aburrell** [comment]
Hi Lois,

If your .radars.sqlite file is empty, then the rest of the routines (more than just rt.py) won’t be able to access any of the necessary hardware information.  I checked on mine and it has rw permissions for root and reading permissions for everyone else.  The file size is 24K and it’s a binary file.  So if yours is empty, that’s a big problem.

To create this file without doing anything else you need to run:

In [1]: import davitpy
In [2]: davitpy.pydarn.radar.updateRadars()

If this is successful you should have this message print out:

“Radars information has been updated."

If you don’t get this message, can you check and see what you have set for these values?

davitpy.rcParams['DAVIT_TMPDIR’]
davitpy.rcParams['SDBREADUSER']
davitpy.rcParams['SDBREADPASS’]
davitpy.rcParams['SDDB’]

I suspect there’s a problem with one of the SD parameters

Cheers,
Angeline

**Comment by asreimer** [comment]
Hi @loisks317,

Sounds to me like you still have a permissions problem as pointed out by @ksterne 

What are the permissions on the /tmp/sd/ directory? If they aren't set so anyone (not just root) can write to /tmp/sd/ then davitpy won't work. Once you have changed the permission, remove the blank .radars.sqlite and fire up davitpy again.

Alternatively, you can create a tmp directory in your home directory and then change the path set in the davitpyrc file.

**Comment by loisks317** [comment]
Hi all, 

Thank you so much for working on this! So I was able to update the radars Angeline which gave me a .radars.sqlite file of ~24 k. 

However, I now have another error message and I get syntax errors when I put 

davitpy.rcParams['DAVIT_TMPDIR’]
davitpy.rcParams['SDBREADUSER']
davitpy.rcParams['SDBREADPASS’]
davitpy.rcParams['SDDB’]

into ipython. The other thing is that I did try changing the write permissions to no avail in the /tmp/sd directory. They now have rwx. 

My new error message is: 
`rad path is=/tmp/sd/
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-d46819793409> in <module>()
      3 rto = raydarn.RtRun(sTime, eTime, 
      4     rCode=radar, beam=beam, freq=freq,
----> 5     outDir='/tmp', nprocs=4)

/usr/local/lib/python2.7/site-packages/davitpy-0.4-py2.7-macosx-10.10-x86_64.egg/davitpy/models/raydarn/rt.py in __init__(self, sTime, eTime, rCode, radarObj, dTime, freq, beam, nhops, elev, azim, hmf2, nmf2, outDir, debug, fext, loadFrom, edens_file, nprocs)
    145 
    146             # Run the ray tracing
--> 147             success = self._execute(nprocs, inputFile, debug=debug)
    148 
    149 

/usr/local/lib/python2.7/site-packages/davitpy-0.4-py2.7-macosx-10.10-x86_64.egg/davitpy/models/raydarn/rt.py in _execute(self, nprocs, inputFileName, debug)
    199 
    200         #print ' '.join(command)
--> 201         process = subp.Popen(command, shell=False, stdout=subp.PIPE, stderr=subp.STDOUT)
    202         output = process.communicate()[0]
    203         exitCode = process.returncode

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    708                                 p2cread, p2cwrite,
    709                                 c2pread, c2pwrite,
--> 710                                 errread, errwrite)
    711         except Exception:
    712             # Preserve original exception in case os.close raises.

/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1333                         raise
   1334                 child_exception = pickle.loads(data)
-> 1335                 raise child_exception
   1336 
   1337 

OSError: [Errno 2] No such file or directory`

I also tried Muhammad's clean install on ubuntu on a virtual box set up and also had no luck with that either. I have had fire wall issues before here in South Africa, but I am running using my VPN, so that shouldn't be it either. 

I do feel like we're getting closer!

**Comment by loisks317** [comment]
GREAT NEWS!

If I use ubuntu in the virtual box, I update the radars, I use 'sudo jupyter notebook', I and use chrome as my browser (all of these are necessary steps!), it works! ! ! ! ! !

Thank you everyone!!! Not the cleanest fix on my end, but I do have it working on my computer with ubuntu now :D

**Comment by MuhammadVT** [comment]
Hi Lois,

It is great! Thank you for letting us know that it finally worked for you.
The problem you have encountered was really a weird one. Please let us know
if you have any other problem in the future.

Best Regards,

SuperDARN Team
