### ISSUE TITLE
dbUtils undefined dictionary

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#208]
In dbUtils.readFromDb, there is a call to a dictionary I can't find being defined anywhere. It's 'refArr' on line 291. There are a few other things in this routine that need more than formatting fixing as well (eg unused variables, missing optional input parameters).

**Comment by aburrell** [comment]
I took a closer look at the refArr problem.  It looks like this object is supposed to have a list of all the possible superDARN data types.  This looks like the type of object that could be useful, but would belong up at a higher level (within rcsetup.py?  Within a different part of the sdio module?).  Are there any thoughts on this?

Also, this routine (readFromDb) is not currently used anywhere, though other dbUtils routines are used (primarily in gme).  Is this routine needed?  My gut feeling is that it should be kept to have a complete set of data tools, but it would be helpful to know what this is supposed to be used for.  Currently, the routine won't work but I don't know how one would test this.

**Comment by asreimer** [comment]
There is a bunch of db stuff that's left in davitpy that we aren't using. My opinion is to remove all of it and to make davitpy depend on the hdw.dat repository instead of using the .radars.sqlite file that we use now. Less maintenance in the long run for us. https://github.com/vtsuperdarn/hdw.dat

**Comment by aburrell** [comment]
I like the idea of removing this and removing stuff we aren't using.  Will this be a defining characteristic of the next (0.6) release?

I wonder about the sustainability of the hdw.dat files, though.  I don't see the institutions going into davitpy to make sure that they're up-to-date.  Perhaps we could run a script that rsyncs with (one of) the mirror site(s).

**Comment by asreimer** [comment]
Currently, we rely on someone regenerating the .radars.sqlite file (Who does that? How is it done? etc.), but yes, I agree that we would have to have some code that checks if the local hdw.dat files are up to date. Also, whatever code does this, it should be platform independent (depend on builtin python libraries). We could probably get away with simply straight up downloading the hdw.dat files without checking which are the most current.

Now that I think of it, we would probably benefit from a system block diagram. I'm surprised we never realized that we don't have one.

**Comment by asreimer** [comment]
HDW.dat is available here and should be downloaded by the user and then set both `SD_RADAR` and `SD_HDW` environment variables to point to the the radar.dat file and hdw.dat directory respectively.
