### ISSUE TITLE
Fix almost all of your install issues/complaints by using platform-independent Miniconda + Virtualenv for single-script install+compile

### ISSUE THREAD

**Issue by scivision** [vtsuperdarn/davitpy#215]
I think a great many of your cross-platform and intra-platform install issues would be solved by NOT messing around with system Python, which can break peoples' systems overall.

Just use [Miniconda Python](http://conda.pydata.org/miniconda.html) and within that, setup a virtualenv for davitpy, so that you don't hose the users' entire operating system if a mistake is made in the install.

Then you would have a _single Python script_ that would install all the Python packages and Python prereqs, plus call the compilers in a **platform-independent** way. A lot of coder and user time will be saved.

Are you interested in such a change? I can do a pull request if you like.

**Comment by scivision** [comment]
Any Python program, all prereqs, all compilation of other languages supporting the Python code should be from a single platform-independent setup.py, and I am familiar with how to do so.

**Comment by asreimer** [comment]
Very interesting. I'm curious about it's compatibility with ipython? We have many ipython notebooks being used by people for examples of how to use davitpy but also for every day processing of data. Another question is how does this mesh with compiling the models that we have wrappers for, which are written in Fortran and C?

We're currently working on a big modification of our codebase (changing docstyle and implementing `logging`), so you might want to hold off on making a pull request until after that. Also, we'll have to get the devs to discuss it of course.
