### ISSUE TITLE
Improvements to file fetching

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#218]
1) Add option to remove .bz2 files after concatonation
2) Add loop to allow 3 attempts at a password, if it is entered interactively

**Comment by asreimer** [comment]
For 1) does this already happen for .gz files? If not, it should also extend to .gz files.

This has to be done carefully. The file validation code in radDataOpen and sdDataOpen was designed to specifically avoid making file fetching and file reading dependent on one another.

**Comment by aburrell** [comment]
It should extend to any concatenated file.  It's pretty easy to do (I've done it before but it's always been lost due to merge issues).  I'll get back to this as soon as I have a chance to update everything to the new version.
