### ISSUE TITLE
Unnecessary routines

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#220]
We have several routines that are simply calls to other routines.  For example, in pydarn.sdio.sdDataRead sdDataOpen calls sdDataPtr without altering any of the input parameters.  All of the input parameters are used.  We should get rid of the redundant routines.

**Comment by aburrell** [comment]
Ug.  Ok, I suppose one is a class and one is a routine, so it's fine.

**Comment by asreimer** [comment]
This might be worth looking into. We only have things set up that way when things were switched over in #47 for backwards compatibility. Might be worth removing that stuff now.
