### ISSUE TITLE
Improving classes

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#221]
We can make our data classes more pythonic by moving the opening and reading routines to be part of the class.

**Comment by mts299** [comment]
This a great idea!
Also, can we discuss why we have multiple classes with the same name?

**Comment by aburrell** [comment]
Yes please!

We should arrange an online developer meeting and discuss some of these things.

**Comment by mts299** [comment]
Like we did with RST? 
I am wondering if some of these issues have been handled or if they could be handled with refactoring/code reviewing (which can be done in a pull request)?

**Comment by aburrell** [comment]
Exactly.  I think all of the active developers have had major life changes this last year and it would be helpful to get back on track.

It's possible some of the issues have been handled, but I did go through them a few months ago and do a clean up.  A lot of them are fairly easy to address, but it's an issue of A) getting someone to do it and B) getting someone to do the testing (often the more difficult bit!).

**Comment by mts299** [comment]
Sounds good, I would take the torch to organize a meeting, but I don't know everyone and whose still involved. So if someone wants to set up a doodle pole that would be great. 
I do have some software developer points to ask about regarding the code, so this meeting would help clear the air on that :) 

I will start looking through some of them and try to address them and test any pull requests that I can.

**Comment by ksterne** [comment]
@mts299, you've got a davitpy-devs google group invite that should help facilitate the process.

**Comment by ksterne** [comment]
Hopefully this was done better in pydarn.  Closing this issue for now since this repo is being deprecated.
