### ISSUE TITLE
Can't find module tsygFort after following installation instructions

### ISSUE THREAD

**Issue by tomharrison920** [vtsuperdarn/davitpy#226]
I am trying to run the tsyganenko model, and followed the davitoy installation instructions as written. I run Linux mint, so ran the installation over debian_dependencies.sh, but when I try to run the tsyganenko model, the tsygFort module can't be found. I was wondering if this has been a problem in the past and, if so, what you could suggest to solve this problem?

Cheers, 

Tom

**Comment by asreimer** [comment]
Hi @tomharrison920,

Could you provide us with a sample of the code you are trying to execute? Much easier to diagnose if we can reproduce the error.

Also, did you follow through the remainder of the installation steps after executing `debian_dependencies.sh`?

**Comment by tomharrison920** [comment]
To the best of my understanding, yes I did follow the remainder of the installation instructions.

The code I tried to execute was simply: 

'from tsyganenko import tsygTrace as T96'

I have since completely removed the davitpy module and tried the whole download again, however, I can now not even find the tysganenko module. I'm afraid I'm not the most experienced python or linux user, so I may be missing some seemingly obvious things. 

I am running linux mint 17.2

During the installation of debian_dependencies.sh there were quite a few errors, but I couldn't work out the specifics.

Thanks, 

Tom

**Comment by asreimer** [comment]
You problem might be that you aren't importing it correctly. 

Since `tsyganenko` is part of the `models` module and `models` is in `davitpy`, you need to:

`from davitpy.models.tsyganenko import tsygTrace as T96`

**Comment by asreimer** [comment]
Hi @tomharrison920,

Did you get your issue resolved?

**Comment by tomharrison920** [comment]
Hi Ashton,


I didn't unfortunately, I ended up getting a colleague to build the plots I needed for me (for some reason he didn't encounter the same issues on his Mac), as I was under quite a large time constraint.


Thank you for your concern though.


Tom

________________________________
