### ISSUE TITLE
Question on converting rawacf files to a usable format

### ISSUE THREAD

**Issue by loisks317** [vtsuperdarn/davitpy#231]
Hi All, 

My advisor just gave me 6 years worth of rawacf fiels, and I need to convert them to velocity, spectral width, and power. So I found in #124 (https://github.com/vtsuperdarn/davitpy/pull/124) on how to read in, store as a Ptr, and then plot the rawacf files. However, I ultimately need to convert them into .fit files essentially. Is there a way to do this in davitpy that I'm missing or do I have to use the RST tool kit? 

 I know I could use the database and transfer, but it would be faster on my end (and with the firewalls we have here...) to just use the rawacf files on the external hard drive given to me. 

Thanks everyone :)

**Comment by ksterne** [comment]
I don't think there is anything in davitpy.  To process rawacf data into fitacf files, you'll need to use the `make_fit` command in the RST code.  That's the SuperDARN standard way.

**Comment by loisks317** [comment]
Thanks - that's a huge help right there. I'm having trouble finding RST documentation past the install.

**Comment by asreimer** [comment]
Hey @loisks317,

It's thankfully pretty simple to convert rawacf to fitacf using RSTLite! Keep in mind that it hasn't necessarily been updated to with the latest version of fitacf2.6 or whatever we're on right now. So you might want to compare the fitacf code on RSTLite with that in RST

Here's the repository for RSTLite: https://github.com/vtsuperdarn/RSTLite
Here's the repository for VTRST3.5: https://github.com/vtsuperdarn/VTRST3.5

RST is sometimes very tricky to compile and install, so I recommend RSTLite, but YMMV.
To make a fitacf file from a rawacf file, once RSTLite is installed:

`make_fit -new rawacf_file.rawacf > fitacf_file.fitacf`

You can also use `make_fitex2` or `make_lmfit` to make those types of fitted files. This paper by @ajribeiro does a good job describing the differences: https://vtechworks.lib.vt.edu/handle/10919/24273

GLHF

**Comment by loisks317** [comment]
Perfect! I will give this a try today - thank you so much !!

**Comment by loisks317** [comment]
So, not too much of a surprise, I am having trouble with the RSTLite install. I'm using a Mac OSX and changed the .bash_profile to have the darwin presets, etc. It seems to install everything and even gives an 'installation complete', however, I get this error when the install.sh is going through the make clean files: 

ld: warning: directory not found for option '-L/Users/loisks/Downloads/RSTLite-master/usr/lib'
ld: unknown option: -Bstatic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [makeall] Error 1

There doesn't seem to be any sort of 'program file' that's generated by the install. I tried executing the make_fit command to see if it would work, and it did not... any ideas?

**Comment by loisks317** [comment]
But I just got it to work on my ubuntu virtual box... [shrugs] Thanks for the patience everyone - let me know if there are any suggestions on how to get it to work for OSX :)

**Comment by ksterne** [comment]
Since this is more related to RST, I'm closing this issue.  @loisks317, I'd suggest any future comments asked on the applicable github repo to keep things more organized.  The short answer is that I don't think there is any Mac support for RST.
