### ISSUE TITLE
Cannot install basemap properly when installing davitpy

### ISSUE THREAD

**Issue by Shirling-VT** [vtsuperdarn/davitpy#236]
Hi, I'm trying to install davitpy on my new computer and meet a problem. After I finished installing it step by step as it is exactly shown in our README.md file, it cannot find the basemap module.  

When I input "**from davitpy import pydarn**" in the ipython command line:
**Loaded davitpyrc file from DaViTpy installation directory. Path: /usr/local/lib/python2.7/dist-packages/davitpy-0.5-py2.7-linux-x86_64.egg/davitpy
/usr/local/lib/python2.7/dist-packages/davitpy-0.5-py2.7-linux-x86_64.egg/davitpy/utils/__init__.pyc -> utils.plotUtils:  cannot import name basemap
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
problem importing fan:  No module named basemap
problem importing musicPlot:  No module named basemap
problem importing proc:  No module named basemap**

I find out that while executing  "**pip install --upgrade basemap**" command in debian_dependencies.sh, these errors will come out:
**Could not find any downloads that satisfy the requirement basemap in /usr/lib/pymodules/python2.7**
Downloading/unpacking basemap
Cleaning up...
No distributions at all found for basemap in /usr/lib/pymodules/python2.7
Storing debug log for failure in /tmp/tmp_u_Y84**

I installed davitpy many times in my old computer, never meet this issue before. Anyone has any idea on why my computer cannot find a satisfactory basemap to install? It is a brand new computer with Ubuntu 14.01 OS.

**Comment by w2naf** [comment]
Hi, Shirling.

Whenever I get that message, I just reinstall basemap from source:
https://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/basemap-1.0.7/

Use the *.gz file at the end, and follow the readme. Sometimes, I end up
having to install some extra dependencies along the way. I just check the
error messages and see what it wants.

Good luck!

Nathaniel

**Comment by Shirling-VT** [comment]
Thanks a lot, Nathaniel! I will definitely give that a try. Even for the
Mac version installation script "*python_install_mac_brew.sh",* I found I
have to install some of the softwares manually.

On Fri, Apr 15, 2016 at 8:04 PM, Nathaniel Frissell <
notifications@github.com> wrote:

> Hi, Shirling.
>
> Whenever I get that message, I just reinstall basemap from source:
>
> https://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/basemap-1.0.7/
>
> Use the *.gz file at the end, and follow the readme. Sometimes, I end up
> having to install some extra dependencies along the way. I just check the
> error messages and see what it wants.
>
> Good luck!
>
> Nathaniel
>
> On Fri, Apr 15, 2016 at 4:27 PM, Shirling-VT <notifications@github.com>
> wrote:
>
> > Hi, I'm trying to install davitpy on my new computer and meet a problem.
> > After I finished installing it step by step as it is exactly shown in our
> > README.md file, it cannot find the basemap module.
> >
> > When I input "*from davitpy import pydarn*" in the ipython command line:
> >
> >
> >
> >
> >
> >
> > *Loaded davitpyrc file from DaViTpy installation directory. Path:
> >
> /usr/local/lib/python2.7/dist-packages/davitpy-0.5-py2.7-linux-x86_64.egg/davitpy
> >
> /usr/local/lib/python2.7/dist-packages/davitpy-0.5-py2.7-linux-x86_64.egg/davitpy/utils/init.pyc
> > -> utils.plotUtils: cannot import name basemap
> > /usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273:
> > UserWarning: Matplotlib is building the font cache using fc-list. This
> may
> > take a moment. warnings.warn('Matplotlib is building the font cache using
> > fc-list. This may take a moment.') problem importing fan: No module named
> > basemap problem importing musicPlot: No module named basemap problem
> > importing proc: No module named basemap*
> >
> > I find out that while executing "*pip install --upgrade basemap*" command
> > in debian_dependencies.sh, these errors will come out:
> > *Could not find any downloads that satisfy the requirement basemap in
> > /usr/lib/pymodules/python2.7*
> > Downloading/unpacking basemap
> > Cleaning up...
> > No distributions at all found for basemap in /usr/lib/pymodules/python2.7
> > Storing debug log for failure in /tmp/tmp_u_Y84**
> >
> > I installed davitpy many times in my old computer, never meet this issue
> > before. Anyone has any idea on why my computer cannot find a satisfactory
> > basemap to install? It is a brand new computer with Ubuntu 14.01 OS.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/vtsuperdarn/davitpy/issues/236>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vtsuperdarn/davitpy/issues/236#issuecomment-210692482>
>



-- 
Best wishes,
Xueling

**Comment by asreimer** [comment]
I am confirming that this is problem on Ubuntu 14.04 now.

I just installed davitpy on a fresh installation of Ubuntu 14.04 and of course I ran the debian_dependencies.sh script but basemap isn't found:

    import mpl_toolkits.basemap as basemap
    ImportError: No module named basemap

So it's not installing correctly.

This fix (which I just tested), is append

    cd /tmp
    git clone https://github.com/matplotlib/basemap.git
    cd basemap/geos-3.3.3
    export GEOS_DIR=/usr/local
    ./configure --prefix=$GEOS_DIR
    make
    make check
    make install
    ldconfig
    cd ..
    python setup.py install

to the debian_dependencies.sh file. I'm making a pull request to fix this.

**Comment by asreimer** [comment]
Issue fixed by #245.
