### ISSUE TITLE
radDataOpen multi-day files don't work properly (fitacf)

### ISSUE THREAD

**Issue by mrwessel** [vtsuperdarn/davitpy#24]
When I use radDataOpen to create a fitacf file containing more than one day of data, I can only get to the end of the first day with radDataReadRec.  Not being fluent in fitacf, I can't even tell whether the subsequent days are present in the file at all.  I don't believe we've changed any of the code surrounding the concatenation for use with our USask fitacf files, so maybe it just doesn't work for any fitacf.

**Comment by asreimer** [comment]
Just did some testing using the current `develop` branch. Seems this bug is fixed.
