### ISSUE TITLE
radDataTypes tmpdir and tmpDir

### ISSUE THREAD

**Issue by ksterne** [vtsuperdarn/davitpy#240]
Working on #214, I noticed an odd issue that happens at:

https://github.com/vtsuperdarn/davitpy/blob/develop/davitpy/pydarn/sdio/radDataTypes.py#L181-L186

It seems as though the input of tmpdir isn't used if it is specified as all references to the temporary directory after these lines go to tmpDir.  Python's case sensitive, right?  So, if you set tmpdir, then it won't get used at all.

Any preference on tmpdir, versus tmpDir?  I can make things consistent with sdDataTypes since I'm working on that as well.

**Comment by asreimer** [comment]
CamelCase is for naming classes and it's variant mixedCase should basically never be used. We've been slowly transitioning things from mixedCase over to namename or name_name.

So, I think you should change it all to tmpdir. No one is likely using tmpDir anyway and we can make sure to highlight this change in the release notes.

Alternatively, if you think this might break some peoples code, you can keep tmpDir and add another tmpdir keyword. Then, in the code, add a deprecation warning for the tmpDir variable as we've done here:

https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/utils/plotUtils.py#L159-L171

for datetime and dateTime.

**Comment by ksterne** [comment]
I read up some more on CamelCase and mixedCase after this, but thank you for the confirmation that thats how we'll approach things.  I've got a pull request going.  Since it was all internal to the code, I don't think I need a depreciation warning.

**Comment by asreimer** [comment]
Fixed by #243
