### ISSUE TITLE
TypeError when do mapDatObj.overlayCnvCntrs()

### ISSUE THREAD

**Issue by Shirling-VT** [vtsuperdarn/davitpy#241]
Hi all,

I found an error when running the convection plotting code in our SuperDARN Data Plotting notebook. It seems that there's some type error somewhere when we try to overlay convection contours in a map plot. The following shows that error message. Anyone can confirm this and has any idea on how to fix this? It seems exist in both present master and develop branch.

---

TypeError                                 Traceback (most recent call last)
<ipython-input-4-70e57d4c587e> in <module>()
     11 mapDatObj = davitpy.pydarn.plotting.plotMapGrd.MapConv(sdate, mObj, ax)
     12 mapDatObj.overlayMapFitVel()
---> 13 mapDatObj.overlayCnvCntrs()
     14 mapDatObj.overlayHMB()

/usr/local/lib/python2.7/site-packages/davitpy-0.6-py2.7-macosx-10.11-x86_64.egg/davitpy/pydarn/plotting/plotMapGrd.pyc in overlayCnvCntrs(self)
    656             vmax=potCntr.max(), vmin=potCntr.min(),
    657             colors = 'DarkSlateGray', linewidths=1.,
--> 658             locator=LinearLocator(12) )
    659         plt.clabel(cntrPlt, inline=1, fontsize=10)
    660         return cntrPlt

/usr/local/lib/python2.7/site-packages/mpl_toolkits/basemap/**init**.pyc in with_transform(self, x, y, data, _args, *_kwargs)
    528             # convert lat/lon coords to map projection coords.
    529             x, y = self(x,y)
--> 530         return plotfunc(self,x,y,data,_args,_*kwargs)
    531     return with_transform
    532 

/usr/local/lib/python2.7/site-packages/mpl_toolkits/basemap/**init**.pyc in contour(self, x, y, data, _args, *_kwargs)
   3633                 mask = np.logical_or(ma.getmaskarray(data),xymask)
   3634                 data = ma.masked_array(data,mask=mask)
-> 3635                 CS = ax.contour(x,y,data,_args,_*kwargs)
   3636         except:
   3637             ax.hold(b)

/usr/local/lib/python2.7/site-packages/matplotlib/**init**.pyc in inner(ax, _args, *_kwargs)
   1810                     warnings.warn(msg % (label_namer, func.**name**),
   1811                                   RuntimeWarning, stacklevel=2)
-> 1812             return func(ax, _args, *_kwargs)
   1813         pre_doc = inner.**doc**
   1814         if pre_doc is None:

/usr/local/lib/python2.7/site-packages/matplotlib/axes/_axes.pyc in contour(self, _args, *_kwargs)
   5642             self.cla()
   5643         kwargs['filled'] = False
-> 5644         return mcontour.QuadContourSet(self, _args, *_kwargs)
   5645     contour.__doc__ = mcontour.QuadContourSet.contour_doc
   5646 

/usr/local/lib/python2.7/site-packages/matplotlib/contour.pyc in **init**(self, ax, _args, *_kwargs)
   1422         are described in QuadContourSet.contour_doc.
   1423         """
-> 1424         ContourSet.**init**(self, ax, _args, *_kwargs)
   1425 
   1426     def _process_args(self, _args, *_kwargs):

/usr/local/lib/python2.7/site-packages/matplotlib/contour.pyc in **init**(self, ax, _args, *_kwargs)
    861         self._transform = kwargs.get('transform', None)
    862 
--> 863         self._process_args(_args, *_kwargs)
    864         self._process_levels()
    865 

/usr/local/lib/python2.7/site-packages/matplotlib/contour.pyc in _process_args(self, _args, *_kwargs)
   1443                 self._corner_mask = mpl.rcParams['contour.corner_mask']
   1444 
-> 1445             x, y, z = self._contour_args(args, kwargs)
   1446 
   1447             _mask = ma.getmask(z)

/usr/local/lib/python2.7/site-packages/matplotlib/contour.pyc in _contour_args(self, args, kwargs)
   1538             warnings.warn('Log scale: values of z <= 0 have been masked')
   1539             self.zmin = z.min()
-> 1540         self._contour_level_args(z, args)
   1541         return (x, y, z)
   1542 

/usr/local/lib/python2.7/site-packages/matplotlib/contour.pyc in _contour_level_args(self, z, args)
   1167         if self.levels is None:
   1168             if len(args) == 0:
-> 1169                 lev = self._autolev(z, 7)
   1170             else:
   1171                 level_arg = args[0]

/usr/local/lib/python2.7/site-packages/matplotlib/contour.pyc in _autolev(self, z, N)
   1149         zmax = self.zmax
   1150         zmin = self.zmin
-> 1151         lev = self.locator.tick_values(zmin, zmax)
   1152         self._auto = True
   1153         if self.filled:

/usr/local/lib/python2.7/site-packages/matplotlib/ticker.pyc in tick_values(self, vmin, vmax)
   1173             vmin, vmax = vmax, vmin
   1174 
-> 1175         if (vmin, vmax) in self.presets:
   1176             return self.presets[(vmin, vmax)]
   1177 

TypeError: unhashable type: 'MaskedArray'

**Comment by asreimer** [comment]
Unlike what I suggested in #246, I don't think this "bug" is fixed.

@Shirling-VT did you ever figure out what was happening here?

**Comment by Shirling-VT** [comment]
Sorry, Ashton, I have no idea about it.

On Thu, May 5, 2016 at 1:49 PM, Ashton Reimer <notifications@github.com>
wrote:

> Unlike what I suggested in #246
> <https://github.com/vtsuperdarn/davitpy/pull/246>, I don't think this
> "bug" is fixed.
>
> @Shirling-VT <https://github.com/Shirling-VT> did you ever figure out
> what was happening here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/vtsuperdarn/davitpy/issues/241#issuecomment-217224354>
>



-- 
Best wishes,
Xueling

**Comment by asreimer** [comment]
Just ran the notebook myself. This is still a problem.

**Comment by ksterne** [comment]
Never got to fixing some of the notebooks.  Closing this issue now for deprecating this repo.
