### ISSUE TITLE
Use install_requires for python package dependencies.

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#250]
Currently, we use a bunch of shell scripts in the `install` directory to install all the dependencies. If we ever want to submit davitpy to pip, we should modify the setup.py file to list the python packages that davitpy depends on (using the install_requires keyword). Also, we should also only use setuptools instead of `numpy.distutils`.

**Comment by ksterne** [comment]
This would have been a great idea to get this repo to pip but we didn't quite make it there (I think).  Closing this issue now for deprecating this repo.
