### ISSUE TITLE
Bug in ae.py

### ISSUE THREAD

**Issue by GPerry306** [vtsuperdarn/davitpy#256]
Keywords 'dbName' and 'collName' in /davitpy/gme/ind/ae.py should be 'dbname' and 'collname', respectively, according to 'getDbConn' function in /davitpy/pydarn/sdio/dbUtils.py.

**Comment by GPerry306** [comment]
The GM indices notebook doesn't seem to work at all for me by the way.

**Comment by MuhammadVT** [comment]
Hi @GPerry306 

Thank you for pointing out the bugs. I have created a pull request #257 to fix this issue. Could you please test it out.

Thanks,

Muhammad

**Comment by asreimer** [comment]
Problem fixed in #257 which has been merged into `develop` now.
