### ISSUE TITLE
OverlayFan polygon doesn't always close

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#258]
When you specify the groundscatter option, you the polygon defining the field of view doesn't close:
![han_mlt_fan_clock](https://cloud.githubusercontent.com/assets/7045886/15962321/3a53e5dc-2f02-11e6-9ac7-0f5204dca6a6.png)

**Comment by asreimer** [comment]
Hey @aburrell, do you have some example code so I can try to reproduce this problem?

Does the same thing happen if you only plot 1 fov, or only if you plot 2?

**Comment by aburrell** [comment]
It’s happened every time I did a groundscatter fov at HAN regardless of the coordinates, number of FOVs, or direction of FOV.  I’ll get some example code up at some point.

**Comment by aburrell** [comment]
Example code:

import datetime as dt
import davitpy
import matplotlib.pyplot as plt
plt.ion()
f = plt.figure()
ax = f.add_subplot(1,1,1)
import mpl_toolkits.basemap as basemap
rad = 'han'
stime = dt.datetime(2006, 10, 1)
hard = davitpy.pydarn.radar.site(code=rad, dt=stime)
m = basemap.Basemap(ax=ax, projection="stere", lon_0=hard.geolon, lat_0=hard.geolat, llcrnrlon=0, llcrnrlat=25, urcrnrlat=70, urcrnrlon=135, resolution="l")
m.drawcoastlines(linewidth=0.5, color="0.6")
m.fillcontinents(color="0.6", alpha=.1)
fov_test = davitpy.pydarn.radar.radFov.fov(site=hard, ngates=75, altitude=350, coords="geo", model="GS", fov_dir="front")
davitpy.pydarn.plotting.overlayFov(m, rad, fovObj=fov_test)


![gs_fov_front_only](https://cloud.githubusercontent.com/assets/7045886/16018878/4cf09476-319e-11e6-8130-bbc9a25530bc.png)

fov_test = davitpy.pydarn.radar.radFov.fov(site=hard, ngates=75, altitude=350, coords="geo", model="IS", fov_dir="back")
davitpy.pydarn.plotting.overlayFov(m, rad, fovObj=fov_test, fovColor="b")

![gs_fov_front_is_back](https://cloud.githubusercontent.com/assets/7045886/16018950/9f4a1dfa-319e-11e6-9c5f-26101c8490d0.png)

**Comment by asreimer** [comment]
The example code fails due the Basemap not having support for datetime objects needed for coordinate conversion.

Modifying the example code to:

    import datetime as dt
    import davitpy
    import matplotlib.pyplot as plt
    plt.ion()
    f = plt.figure()
    ax = f.add_subplot(1,1,1)
    import mpl_toolkits.basemap as basemap
    rad = 'han'
    stime = dt.datetime(2006, 10, 1)
    hard = davitpy.pydarn.radar.site(code=rad, dt=stime)
    m = davitpy.utils.mapObj(ax=ax, projection="stere", lon_0=hard.geolon, lat_0=hard.geolat, llcrnrlon=0, llcrnrlat=25, urcrnrlat=70, urcrnrlon=135, resolution="l")
    m.drawcoastlines(linewidth=0.5, color="0.6")
    m.fillcontinents(color="0.6", alpha=.1)
    fov_test = davitpy.pydarn.radar.radFov.fov(site=hard, ngates=75, altitude=350, coords="geo", model="GS", fov_dir="front")
    davitpy.pydarn.plotting.overlayFov(m, rad, fovObj=fov_test)
    
    fov_test = davitpy.pydarn.radar.radFov.fov(site=hard, ngates=75, altitude=350, coords="geo", model="IS", fov_dir="back")
    davitpy.pydarn.plotting.overlayFov(m, rad, fovObj=fov_test, fovColor="b")

I am able to reproduce the above plot. 

Any idea why this is happening?

**Comment by aburrell** [comment]
Odd that it works for ionospheric backscatter without this support.

**Comment by aburrell** [comment]
This is wierd.  date_time should only be important if “geo” is not used.

**Comment by aburrell** [comment]
Ok, thing 1)  In the original example I had added:

m.dateTime=stime

Which is why I didn't get an error.  But I forgot I added that.

**Comment by asreimer** [comment]
Ah ok that makes sense. Any idea why the FOV isn't closing on the GS plot?

**Comment by aburrell** [comment]
Ok, I figured it out.  The fov object doesn't save the model it used to create the object, so you have to keep specifying it.

**Comment by aburrell** [comment]
We should probably add a model to the fov object and have routines check for it.  If it doesn't exist, it can default to IS but spit out a warning.

**Comment by aburrell** [comment]
In [79]: print fov_test
latCenter: (16, 75)                      
lonCenter: (16, 75)                      
latFull: (17, 76)                      
lonFull: (17, 76)                      
slantRCenter: (16, 75)                      
slantRFull: (17, 76)                      
beams: (16,)                      
gates: (75,)                      
coords: geo

^
model: GS

**Comment by asreimer** [comment]
Awesome! And I agree with that fix. Luckily it's a simple fix too :)

**Comment by aburrell** [comment]
Yes...

Unfortunately I'm heading offline since it's 21:30 and I'm still in the office sans dinner :'(

**Comment by asreimer** [comment]
Yes! Go home and eat. This can wait.

**Comment by aburrell** [comment]
As promised!  Pull request #269

**Comment by asreimer** [comment]
Excellent! I have some things to do this afternoon, but I'll get it tested and merged tonight.

**Comment by asreimer** [comment]
Issue resolved.
