### ISSUE TITLE
ImportError when trying to make RTI plot

### ISSUE THREAD

**Issue by ndestefano** [vtsuperdarn/davitpy#263]
Hello,

I am trying to reproduce the MUSIC notebook (https://github.com/vtsuperdarn/davitpy/blob/master/docs/notebook/MUSIC.ipynb). I can successfully load the file and see that there is fit data in there (input 4 of the notebook). However when I try to make the RTI figure (input 8) I get the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-5fe316e7ade9> in <module>()
----> 1 fit = pydarn.plotting.musicRTI(dataObj)

/usr/local/lib/python2.7/site-packages/davitpy-0.5-py2.7-macosx-10.11-x86_64.egg/davitpy/pydarn/plotting/musicPlot.pyc in __init__(self, dataObject, dataSet, beam, coords, xlim, ylim, axis, scale, plotZeros, max_sounding_time, xBoundaryLimits, yBoundaryLimits, yticks, ytick_lat_format, autoScale, plotTerminator, axvlines, axvline_color, secondary_coords, plot_info, plot_title, plot_range_limits_label, cmap_handling, cmap, bounds, norm, plot_cbar, cbar_ticks, cbar_shrink, cbar_fraction, cbar_gstext_offset, cbar_gstext_fontsize, model_text_size, y_labelpad, **kwArgs)
    555 
    556         from scipy import stats
--> 557         from rti import plotFreq,plotNoise
    558 
    559         if axis is None:

ImportError: cannot import name plotFreq
```

When I look for the function plotFreq I do not find it in rti.py. In fact, I searched the entire repository and I don't see it. There is a plot_freq function in rti but it has a different parameter list. Do I have some sort of dependency that's missing?

**Comment by w2naf** [comment]
Hi there. No, you are not missing anything... Something broke when were
trying to do a large davitpy update.

I'll try to patch it later today and get back to you.

Best,
Nathaniel

**Comment by w2naf** [comment]
Hi, @ndestefano . https://github.com/vtsuperdarn/davitpy/pull/265 will fix your problem.

Give it a try and let me know. Thanks!

**Comment by ndestefano** [comment]
That seemed to work, thanks!

**Comment by salsrag** [comment]
Nathaniel,

 

What is your current E-mail address?

 

Ray

**Comment by w2naf** [comment]
Hi, Ray. 

My new e-mail is nathaniel.a.frissell@njit.edu.

Hope all is well,
Nathaniel
