### ISSUE TITLE
Problems getting data

### ISSUE THREAD

**Issue by ReedOnly** [vtsuperdarn/davitpy#272]
Hi I'm getting this errors while downloading data:

```
"ERROR:paramiko.transport:SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
ERROR:paramiko.transport:
ERROR:root:can't connect to sd-data.ece.vt.edu with username and password"
```

Is any settings changed on the server side, or de we need updated login information?

Regards,
Kristian Reed

**Comment by asreimer** [comment]
Hey @ReedOnly,

Can you post the code that you are using that is giving you this error? I'm not having any trouble connecting and I haven't changed any of the default login credentials.

**Comment by ReedOnly** [comment]
Hi,

Yeah, seems like it's working from here I'm sitting now on my laptop too. I've sent you an e-mail!

**Comment by ksterne** [comment]
This related to an entry on the sd-data.ece.vt.edu server's blocked list.  It should be cleared up now.  Though, care should be taken as to how that IP address ended up on our blocked list in the first place.
