### ISSUE TITLE
Refactor hdw.dat file handling

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#278]
How we handle hdw.dat files in davitpy IMHO is unnecessarily complicated by the usage of sqlite. Instead, we should just parse the hdw.dat files directly from https://github.com/vtsuperdarn/hdw.dat

For example, who is in charge of maintaining the radars.sqlite file? What code is used to generated this file?

We should refactor davitpy so that it doesn't use sqlite for this anymore.

Discuss?

**Comment by aburrell** [comment]
I'm in favour of this.  I also think this is something we should sort at AGU (basically post our next release).

**Comment by asreimer** [comment]
Today, I recently encountered the issue where fetching the radars.sqlite file is not possible when trying to use davitpy at SRI (ports are blocked).

We tried very hard to get rid of environment variables when the davitpyrc file was implemented, but we (me actually...) missed a couple, specifically `SD_HDWPATH` and `SD_RADAR`. They are used [here](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/radar/radInfoIo.py#L64), [here](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/radar/radInfoIo.py#L153), and [here](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/radar/radInfoIo.py#L341-L342). They might be used in other places too.

Additionally, we do not currently provide users with instructions on where they can find the hdw.dat and radar.dat files... Whoops :)

**Comment by asreimer** [comment]
This issue should be prioritized. See https://github.com/vtsuperdarn/davitpy/issues/363, https://github.com/vtsuperdarn/davitpy/issues/339, 

At the very least, we should update the documentation in the README.md in the install instructions/known issues. [These lines have been added in a previous pull request](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/radar/radInfoIo.py#L66-L91) but it seems users aren't seeing them.

**Comment by ksterne** [comment]
This issue continues in other frames/codebases.  However, it should be noted that unless you are on the Virginia Tech network, the hdw.dat MongoDB port will be blocked.  There are some solutions that exists for downloading your own copy of the hdw.dat files from [this repo](https://github.com/vtsuperdarn/hdw.dat) and updating the local `.radars.sqlite` file locally.

Closing this issue for deprecation of this repo.
