### ISSUE TITLE
Error reporting in radar routines

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#279]
When running davitpy.pydarn.radar.site and other radar routines, the function input isn't checked and error handling is absent.  This can make it difficult to know why any particular call crashed.

**Comment by asreimer** [comment]
@ksterne implemented some input checking in `acfPlot` in #292

**Comment by ksterne** [comment]
Starting to work on input checks for the `pydarn.radar.site` class in the enhancements-site_inputs_checks branch.  With any luck, I'll try to get to the other classes in the `radStruct.py` file.   Certainly something we should try to get done in *every* file before the first version, but I'll try to knock off where and what I can.

**Comment by ksterne** [comment]
Looks as though this issue was resolved but never closed.  Closing this issue for now with the deprecation of this repo.
