### ISSUE TITLE
Q: User mailing list? 

### ISSUE THREAD

**Issue by paalge** [vtsuperdarn/davitpy#281]
I'm getting into using davitpy for analysing SuperDARN data, and I'm foreseeing having to extend the capabilities of davitpy, as the project I'm working on requires handling the data in a way I haven't been able to find tools for in davitpy.
In this process I was wondering if there is a mailing list or similar where I can ask questions about what is present in the code, as I don't feel like Issues is the correct place for such questions. Is the google group for devel intended for such questions?
I know for instance matplotlib just moved theirs to python.org (both users and devel)

**Comment by ksterne** [comment]
Hello @paalge,

I see your request to join the davitpy-dev google group and have accepted that request.

You bring up a good point here, should we have another list that is more for users than for developers?  This would be a good place that we could send out notices on new releases as they come out.  We don't really have a way to keep a list or contacts for people that we know are out there and using davitpy.  Any thoughts?

I can set this up and add current members of the davitpy-dev group as well as any others that we've heard from.

**Comment by paalge** [comment]
I've been using a lot of different packages over the years (as well as contributing to them), and I've found, especially when you're now to it, that the ability search user mailing lists for solutions, as well as asking a question really good. It also gives an idea of the community and what part of your product they are using. 
Since davitpy (I'm sorry to say) lacks a comprehensive documentation, a user mailing list could be a good solution for now, though it is dependent on the number of people who use it.

As you mention it would also be a good place to announce the releases and issues (like the hdw issue yesterday, which I had, but didn't find here before today).

**Comment by asreimer** [comment]
We have a DaViTpy-users Google Group: https://groups.google.com/forum/#!forum/davitpy-users

**Comment by ksterne** [comment]
OH, well look at that...and I'm even an owner.  There's no mention of this on the main README.md file...maybe we should change that.

**Comment by ksterne** [comment]
OK all, I've hotfixed the README.md file with e0f1714 to include some info/encouragement about joining the davitpy-users list.  Thanks @asreimer, for reminding me this existed!  I believe this can be closed now.
