### ISSUE TITLE
MLT conversion issue when doing the convection map

### ISSUE THREAD

**Issue by Shirling-VT** [vtsuperdarn/davitpy#286]
Hi,

Here is the code when we do the convection map:

import datetime
import matplotlib.pyplot as plt
import davitpy.pydarn.plotting.plotMapGrd
from davitpy.utils import *
fig = plt.figure()
ax = fig.add_subplot(111)
sdate = datetime.datetime(2016, 3, 1, 9, 0)
mObj = plotUtils.mapObj(boundinglat=50., datetime=sdate,
                        gridLabels=True, coords='mlt')
mapDatObj = davitpy.pydarn.plotting.plotMapGrd.MapConv(sdate, mObj, ax)
mapDatObj.overlayMapFitVel()
mapDatObj.overlayCnvCntrs()
mapDatObj.overlayHMB()
plt.show()

Usually, we set the mlt coordnates in the mapObj function, but we keep the parameter plotCoords in the davitpy.pydarn.plotting.plotMapGrd.MapConv rountine, with which we can choose between the mlt and mag coordinates as well, even though we have already set the coords in the mapObj. I found this really confusing and there are typos and other importing issues in the below code, which will give you an error message when you use plotCoords to set the coordinates:

        # check if hemi and coords keywords are correct
        assert(hemi == "north" or hemi == "south"), \
            logging.error("hemi should either be 'north' or 'south'")
        assert(plotCoords == 'mag' or **coords** == 'mlt'), \
            logging.error("error, coords must be one of 'mag' or 'mlt'")

        # mlt conversion stuff
        if self.plotCoords == 'mlt':
            epoch = timeUtils.datetimeToEpoch(**strtTime**)
            mltDef = aacgm.mltFromEpoch(epoch,0.0) * 15.
            lonShftFit += mltDef
            gridArr[1,:] = numpy.mod( ( gridArr[1,:] + lonShftFit ) / 15., 24. )
        else:
            gridArr[1,:] = ( gridArr[1,:] + lonShftFit ) 

**coords**  here should be replaced with plotCoords, and "strtTime" is definitely a typo. timeUtils and aacgm are not imported well before using. Even if I corrected all these issues, it still does not work correctly when  using **mapDatObj = davitpy.pydarn.plotting.plotMapGrd.MapConv(sdate, mObj, ax, plotCoords='mlt')** to do the plotting. I guess the reason is that, in MapConv if we set the plotCoord to mlt, it will do the mlt conversion in the code and set the coords in mapObj to mlt and do the mlt conversion twice in mapObj rountine. Therefore, let alone the issues of the mlt conversion code in MapConv, I find it unnecessary to add another plotCoords parameter to set the coordinate, since we could do it in the mapObj. Any thought?

Best wishes,
Xueling

**Comment by paalge** [comment]
Hi
I agree that there are issues with the MLT, there is amongst others the strange factor of 15 that shows up several places in the code, which changes the magnetic longitude.
I seems like the MLT plotting has not been tested well enough.

**Comment by asreimer** [comment]
@paalge 

Ya, the convection map plotting in general needs some work. The MLT plotting is fine. The convection maps just don't put noon at the top.

By the way, the "strange" factor of 15 is the quotient of 360/24 (the number of degrees of longitude per hour of MLT). This might not be needed anymore depending on where it shows up. Which function are these factors present in?

**Comment by mrwessel** [comment]
I have a new-and-improved convection map module that is not quite ready to see the light of day, but someday soon I will unleash it on a pull request.  In that module, noon at the top will be default.  For MLT in general, when I put the existing capability into davitpy I did not set a separate default for MLT (there was already a default lat_0 and lon_0).

**Comment by asreimer** [comment]
Turns out that the usage of `plotCoords` here is completely unnecessary. @Shirling-VT and I have been debugging this together here and found a major bug that occurs when you use a 'mag' coords for the `mapObj` and 'mlt' for `plotCoords`.

I'll be issuing a pulling request very soon that fixes this issue.

**Comment by ksterne** [comment]
Can this issue now be closed since #296 is merged in?  @Shirling-VT?

**Comment by Shirling-VT** [comment]
@ksterne Sure.
