### ISSUE TITLE
install issue with davitpy_path

### ISSUE THREAD

**Issue by arfogg** [vtsuperdarn/davitpy#309]
After (seemingly) successfully running install there is an error importing davitpy that stems from the rcPARAM davitpy_path.  @aburrell has commented this out in the past to get around this issue, but that's not a real solution for everyone.

    $ python setup.py install --user
    $ipython
    
    In [1]: import davitpy as dp
    ---------------------------------------------------------------------------
    RuntimeError                              Traceback (most recent call last)
    <ipython-input-1-cccfcdb2eb5a> in <module>()
    ----> 1 import davitpy as dp
    
    /home/a/arf18/source/davitpy/davitpy/__init__.py in <module>()
        608 
        609 # Set up the rcParams dictionary
    --> 610 rcParams = rc_params()
        611 
        612 #TO DO
    
    /home/a/arf18/source/davitpy/davitpy/__init__.py in rc_params(fail_on_error)
        504         return ret
        505 
    --> 506     return rc_params_from_file(fname, fail_on_error)
        507 
        508 

    /home/a/arf18/source/davitpy/davitpy/__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
        592     iter_params = six.iteritems(defaultParams)
        593     config = RcParams([(key, default) for key, (default, _) in iter_params
    --> 594                                       if key not in _all_deprecated])
        595     config.update(config_from_file)
        596 
    
    /home/a/arf18/source/davitpy/davitpy/__init__.py in __init__(self, *args, **kwargs)
        377     def __init__(self, *args, **kwargs):
        378         for k, v in six.iteritems(dict(*args, **kwargs)):
    --> 379             self[k] = v
        380 
        381     def __setitem__(self, key, val):
    
    /home/a/arf18/source/davitpy/davitpy/__init__.py in __setitem__(self, key, val)
        391                 return
        392             try:
    --> 393                 cval = self.validate[key](val)
        394                 if key == 'verbosity':
        395                     level_dict = {'silent': 60,
    
    /home/a/arf18/source/davitpy/davitpy/rcsetup.pyc in validate_path_exists(s)
         85         return s
         86     else:
    ---> 87         raise RuntimeError('"%s" should be a path but it does not exist' % s)
         88 
         89 
    
    RuntimeError: "" should be a path but it does not exist
    
    In [2]: debug
    > /home/a/arf18/source/davitpy/davitpy/rcsetup.py(87)validate_path_exists()
         85         return s
         86     else:
    ---> 87         raise RuntimeError('"%s" should be a path but it does not exist' % s)
         88 
         89 
    
    ipdb> print s
    
    ipdb> up
    > /home/a/arf18/source/davitpy/davitpy/__init__.py(412)__setitem__()
        410         except KeyError:
        411             raise KeyError('%s is not a valid rc parameter.\
    --> 412 See rcParams.keys() for a list of valid parameters.' % (key,))
        413 
        414 
    
    ipdb> print key
    DAVITPY_PATH

**Comment by ksterne** [comment]
Hello @arfogg, I'm not sure I can completely follow your problem here.  In the default davitpyrc, there is not a davitpy_path variable.  Is this is what you're noting is getting set, possibly incorrectly?

**Comment by aburrell** [comment]
It's not a variable in davitpyrc, but rcsetup.py sets it on line 232.  It looks like the error handling for the variable `path` set on line 220 is not sufficient.

I was able to complete the install by deleting line 232 (it has no effect on the functionality).  Do we use DAVITPY_PATH anywhere?  I couldn't find an instance.  Do you know why we set it?

**Comment by kherli** [comment]
I got the above error also... but as long as I am not in the directory containing davitpy then everything works fine

**Comment by asreimer** [comment]
I'm responding rather late to this. Thesis still not done, but this is a nice break.

As @kherli mentioned, running davitpy outside of the installation directory works fine. So, why are people running davitpy from the installation directory (@aburrell  @arfogg )? You install it to your user python site-packages and it gets imported from there. Is there some advantage? You can actually delete the source directories after running setup.py if you just want to use it.

Deleting `DAVITPY_PATH` from rcsetup.py is _not_ a good solution to this problem. It creates problems for the IRI, HWM, and RAYDARN. If you aren't using those models, then I guess you are fine, but it's a bad bandaid.

Further investigation as to the actual cause here is required.

**Comment by asreimer** [comment]
Ok, this is actually really simple.

If you are in the source directory, the code that looks for the installation location finds the davitpy package in the source directory. At this point, it finds that your relative path is "", an empty string.

The offending line of code is line 412 in `davitpy/davitpy/rcsetup.py`

    path = os.path.split(os.path.dirname(__file__))[0]

should be replaced by

    path = os.path.abspath(os.path.split(os.path.dirname(__file__))[0])

because a relative path of "" is not a valid path. The absolute path of "" works much better.

Thanks for reporting this. I'll make a pull request.

I would still like to know why people are running davitpy from the source directory though!

**Comment by asreimer** [comment]
Bug fixed in https://github.com/vtsuperdarn/davitpy/pull/326

Thanks for reporting!

**Comment by aburrell** [comment]
We weren't running form the source directory, this was a problem we encountered when installing a common version of davitpy in a shared directory on a cluster.  The first person to use davitpy could use as is, and then the next person wouldn't be able to (also no idea why, this also confused the IT people).  @arfogg , do you think you could test the installation on alice and then see if you and Sam can both use it?  You can  make a differently-named directory for it in the data directory and leave the current installation alone.  The directions I left should still be good.

**Comment by asreimer** [comment]
I'm only able to go off of the information posted here. There definitely was a bug with running davitpy from the installation directory (actually, from any directory called davitpy).

As for why it isn't working on a server we don't have access to and no debugging information for, that's a whole other issue :)

It was probably already looked at, but it really sounds like a permissions problem to me. Any reason why people aren't running their own analysis code from their own python virtual environments on the server? That's the config I have running at work for the server I manage and it has been working nicely.

**Comment by aburrell** [comment]
That requires a higher level of programming skill than most of the users have!  What we really would have liked was a version of davitpy installable and managable through something like anaconda or pip :-P

I’m pretty confident this will fix things, but I’m no longer able to access the environment to test it.

**Comment by asreimer** [comment]
Python virtual environments are really not much harder than installing anaconda or using pip.

I definitely agree that we should get this to a point where it can be installed using pip or anaconda. We'll get there.

Seems this issue is resolved by #326 then.
