### ISSUE TITLE
sdDataOpen and errornous data entries

### ISSUE THREAD

**Issue by paalge** [vtsuperdarn/davitpy#318]
Hi

I've been reading in large SuperDARN mapex datafiles (several years).
In this process I've found it necessary to handle missing time points, as `readRec()` on a `sdDataPtr`, sometimes returns `None` for certain times. I haven't been able to move past it with the open pointer, and I have to result to a new pointer with `noCache=True` using `sdDataOpen()`. With years of data to read in this turns into a very slow process.
Is there a fix for this? 

An example for testing this is  (make sure tmp dir is empty). If run twice this does not fail, as the failing command uses the file made by the last ptr.
```
import davitpy
import datetime

start = datetime.datetime(2013,10,2,23,45)
end = datetime.datetime(2013,10,8,0,0)

ptr = davitpy.pydarn.sdio.sdDataOpen(start,hemi="south",eTime=end)
rec = ptr.readRec()
while(rec):
    print("End time",rec.eTime)
    curtime = rec.eTime # Save end time
    rec = ptr.readRec()

print("Her last read time ",curtime, " is not the end time ",end)

# Make a new pointer 10 min after end time, this will not work
ptr.close()
ptr = davitpy.pydarn.sdio.sdDataOpen(curtime+datetime.timedelta(minutes=10),hemi="south",eTime=end)
# Try and read from it
print("This doesn't work")
print(ptr.readRec())

# Do the same, but with noCache
ptr.close()
ptr = davitpy.pydarn.sdio.sdDataOpen(curtime+datetime.timedelta(minutes=10),hemi="south",eTime=end,noCache=True)
# Try and read from it
print("This works")
print(ptr.readRec().eTime)
```

**Comment by asreimer** [comment]
Data fetching is completely broken now that the VT server is no longer open. Probably won't be able to fix this.
