### ISSUE TITLE
Co-rotation

### ISSUE THREAD

**Issue by jpreistad** [vtsuperdarn/davitpy#320]
I am not sure if this is the correct place to ask, if not maybe someone can point me to the right person. I am wondering of anything has been done with the plasma velocity data (any of the dataproducts available through davitpy) that takes into account that Earth rotates? I am using an MLT grid for plotting, and in that frame the radar rotates with the Earth, and I want to express the velocities in the same (non-rotating) frame. To me it seems obvious that this should be corrected for, so i just want to make sure that it has not already been done.

Cheers,
Jone Peter Reistad
Postdoc, University of Bergen, Norway

**Comment by aburrell** [comment]
This is perhaps not the best place for such questions, but it is a place where you can contact SuperDARN people easily.

There is a way to take into account the Earth’s rotation, and this is done when making the grid files from the fit files.  davitpy/pydarn is an analysis tool, and making grid files is considered processing, so it’s not done here.  Instead, the RST code is used.  You can find the RST code at:

https://github.com/SuperDARN/rst

The routine within this code base you’re looking for is make_grid.  There many knowledgeable people working actively on this code who will be happy to answer any questions that pop up.

Good luck!
Angeline

---------------------------------------------------------------
Dr. Angeline G. Burrell
Postdoctoral Research Fellow

Department of Physics
William B. Hanson Center for Space Sciences
University of Texas at Dallas

p: +1 (972) 883-3902
w: utdallas.academia.edu/AngelineBurrell<http://utdallas.academia.edu/AngelineBurrell>
---------------------------------------------------------------


On 25 Aug 2017, at 02:26, jpreistad <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure if this is the correct place to ask, if not maybe someone can point me to the right person. I am wondering of anything has been done with the plasma velocity data (any of the dataproducts available through davitpy) that takes into account that Earth rotates? I am using an MLT grid for plotting, and in that frame the radar rotates with the Earth, and I want to express the velocities in the same (non-rotating) frame. To me it seems obvious that this should be corrected for, so i just want to make sure that it has not already been done.

Cheers,
Jone Peter Reistad
Postdoc, University of Bergen, Norway

**Comment by jpreistad** [comment]
Thank you for your response. I have downloaded what I think is grid files, by invoking the following command in davitpy: 
data =  pydarn.sdio.sdDataReadRec(ptr)

Here, data.fType='grdex', which is what makes me suspect this is what you call a grid file. Is there any reason to believe that something is done with respect to co-rotation in the data I retrieve by the above formula?

Cheers,
-Jone

**Comment by aburrell** [comment]
You have downloaded a grid file, but there is no reason to think that anything was done with respect to co-rotation because that is not the standard processing and anything you download from the standard davitpy routines will be standard files.  Referring back to my previous response, there is a way to take into account the Earth’s rotation, and this is done when making (not downloading) the grid files from the fit files.  To do this you need to use the RST code.

**Comment by jpreistad** [comment]
Thank you for the clarification.
-Jone

2017-08-30 15:47 GMT+02:00 Angeline Burrell <notifications@github.com>:
