### ISSUE TITLE
overlayFov is broken by changes to fov generation code

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#321]
Currently, in the `develop` branch, overlayFov is unable to plot FOVs for all SuperDARN radars without producing wildly wonky results. 

![superdarnfovs](https://user-images.githubusercontent.com/4604819/30244294-5173c626-9570-11e7-8009-54523ab2e70f.png)

Here's the code I used to produce this figure:

    from davitpy.pydarn.radar import *
    from davitpy.pydarn.plotting import *
    from davitpy.utils import *
    import datetime as dt
    from matplotlib import pyplot
    
    fig = pyplot.figure(figsize=(16,8))
    ax1 = fig.add_subplot(121)
    m1 = plotUtils.mapObj(boundinglat=30., gridLabels=True,ax=ax1)
    overlayRadar(m1, fontSize=8, plot_all=True, markerSize=5)
    overlayFov(m1,plot_all=True)
    ax2 = fig.add_subplot(122)
    m2 = plotUtils.mapObj(boundinglat=-30., gridLabels=True,ax=ax2)
    overlayRadar(m2, fontSize=8, plot_all=True, markerSize=5)
    overlayFov(m2,plot_all=True)
    fig.show()

If you turn on the logging to be `debug-annoying` you will see a TON of warnings like this:

`WARNING:root:Accuracy on height calculation (5.0) not reached quick enough. Returning nan, nan.`

This is an issue that goes back until 0.5-master. 0.5-master is able to make sane looking plots. Everything after that has this bug that makes the crazy plots. Something changed in the fov generation code between then and now that is producing NaNs when it really shouldn't be.

**Comment by asreimer** [comment]
Since this affects 2 of our master branch releases, I'd say this is a critical bug that needs a hotfix.

**Comment by aburrell** [comment]
Agreed.  I'm happy to do some work on it once I get the two pull requests I'm working on done.

**Comment by aburrell** [comment]
Ok, I found where the bug is and know how to fix it.  Pull request coming soon...

**Comment by aburrell** [comment]
Addressed in #324

**Comment by mts299** [comment]
I assume this issue is fixed now?

**Comment by aburrell** [comment]
THanks for the reminder
