### ISSUE TITLE
bad asserts in fetchUtils

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#330]
The `outdir` asserts found [here](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/sdio/fetchUtils.py#L197) and [here](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/sdio/fetchUtils.py#L433) are bad. 

Specifically the `outdir[-1] == "/"` part is nasty.

Using `os.path.join` automatically handles all of the slash problems with joining paths together. So we should remove this from the asserts.

Additionally, line [652](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/sdio/fetchUtils.py#L652) needs to be changed to:

    tf = os.path.join(outdir, rf)

**Comment by ksterne** [comment]
Hey @asreimer, is this hotfix worthy?  Or just needs to be updated for next release?

**Comment by ksterne** [comment]
Time to close this @asreimer?

**Comment by asreimer** [comment]
Fixed in #336
