### ISSUE TITLE
Rules for davitpyrc location

### ISSUE THREAD

**Issue by lgretton** [vtsuperdarn/davitpy#335]
The documentation states that davitpyrc is looked for either in the user's home directory or in davitpy/davitpy/davitpyrc. This doesn't seem to be the case. After experiencing some problems getting a centrally-installed version of davit to work for multiple users, the following rules seem to be in force to locate davitpyrc:

1. Current working directory
2. Directory pointed to by the environment variable $DAVITPYRC, if defined
3. $XDG_CONFIG_HOME/davitpy if $XDG_CONFIG_HOME is defined
4. $HOME/.config/davitpy
5. Finally in davitpy/davitpy/davitpyrc

If I'm right then this is all very good, but the readme file just needs an update to reflect this behaviour.

**Comment by asreimer** [comment]
There's a bug that's been fixed in #326. Number 1 in your list is supposed to be the home directory of the user. It's not a typo in the readme.
