### ISSUE TITLE
Feature request: plotting data external to DavitPy on coastlines

### ISSUE THREAD

**Issue by johncoxon** [vtsuperdarn/davitpy#340]
I notice that DavitPy has the ability to plot maps of data on coastlines. What would be incredibly useful is a generic class which would let me specify a coordinate system (e.g. AACGM) and then pass some data to plot on top of the coastlines. I've had a look at the code that does the coastline plotting and as far as I can tell, it's modifying the `Basemap` class in some way to achieve this. I'd be interested in learning more about how exactly this is achieved so that I could work on this feature and perhaps submit a pull request….

(Also, is there a Slack or similar for DavitPy where I can ask stupid questions about how I might go about doing this?)

**Comment by aburrell** [comment]
Hi @johncoxon,  The modification of the basemap class is simply adding a datetime object, so that time-dependent coordinate systems (such as AACGM) can be used.  Please do take a hack at this and see what you can do!

Right now davitpy doesn't use slack, but we have users and developers google groups.  Are you a part of that already?

**Comment by johncoxon** [comment]
No, I'm not – can you point me at a link? I'm not sure the sort of questions I want to ask are well-suited to an email list, but the users group sounds useful!

**Comment by aburrell** [comment]
https://groups.google.com/forum/#!forum/davitpy-users

I agree, and looking at the issues I think a slack group is needed.

**Comment by johncoxon** [comment]
It turns out that this is already possible using the calls in `docs/notebook/maps.ipynb`, so I will close this as it's a duplication of existing functionality!
