### ISSUE TITLE
Python 3, remove deprecated modules

### ISSUE THREAD

**Issue by scivision** [vtsuperdarn/davitpy#342]
* Basemap is [deprecated](https://github.com/SciTools/cartopy/issues/920#issuecomment-321329691), upgrade to its replacement CartoPy
* gently, in phases, do pull requests for Python>=3.5. I closed my own pull requests #311 and #312 because they were too big at once.
  * NumPy is dropping Python 2.7 new releases as of Jan 1, 2019.
  * Matplotlib 3.0 (summer 2018) requires Python>=3.5
  * over half of new Python devel work has been Python 3 since 2016.
  * I have been _requiring_ Python 3.5 and 3.6 for most of my repos, with a very wide and reasonably large audience and get almost no complaints

**Comment by aburrell** [comment]
@scivision , I think replacing the deprecated modules is a good place to start.  After that, it may be worthwhile to do the python 3 updates and add unit tests at the same time.  That way we can sensibly do testing on a larger codebase.

**Comment by ksterne** [comment]
Certainly agree here.  Seems as though we'll have a good bit of work ahead of us to get caught up to python3!

**Comment by ksterne** [comment]
One of the main reasons we realized this repo had become too bloated for us to manage.  Closing this issue now as we never fully upgraded to python3 and the new dependencies and davitpy is being deprecated.
