### ISSUE TITLE
MSIS

### ISSUE THREAD

**Issue by donalmur** [vtsuperdarn/davitpy#35]
Hi 
I have been trying msis and do not find that the Texo changes with f10.7 as I would expect in fact I alway get the same value Texo= 1027.3K
Any comment?

**Comment by asreimer** [comment]
He @donalmur,

I just finished creating a unit test for NRLMSISE-00 in davitpy, based off of the test code included in the [MSIS source code](ftp://hanna.ccmc.gsfc.nasa.gov/pub/modelweb/atmospheric/msis/nrlmsise00/). MSIS as is found in davitpy's current master and develop branches.

So unless there is a bug in the MSIS code itself (which the author, Picone, will have to fix), I have no idea why you haven't seen Texo vary with F10.7/AP as you expect.

**Comment by donalmur** [comment]
Hi

Ah I found the reason. Turns out that they fix the Texo for altitudes below 100 km (if i remember correctly) . I have suggested that while they may have to do that to generate the results below 100 km that they at least report the correct value.  If one wants to know the correct value then you have to select a height above the cutoff

Regards and thanks for your attention


Donal

---------------------------------------------------------------
Donal Murtagh
Prof Global Environmental Measurements
Chalmers tekniska högskola
tel +46 31 772 56 51
donal.murtagh@chalmers.se <mailto:donal.murtagh@chalmers.se>
