### ISSUE TITLE
Concern with gsMapSlantRange function

### ISSUE THREAD

**Issue by egthomas** [vtsuperdarn/davitpy#353]
I have a concern with the function `gsMapSlantRange` added in commit 6feea98 to `radFov.py`.  I'm not sure that [Bristow et al. [1994]](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/93JA01470)'s range calculation is applicable here.  The equation in that paper is solving for the ground range to the ionospheric reflection point (`D`) and not the slant range to the reflection point (`R/2`).

I'm also not convinced the equation in that paper is even correct for solving the ground range to the ionospheric reflection point of a ground scatter echo, but that's another matter.

**Comment by egthomas** [comment]
I don't suppose this issue came up during the developer telecon?

**Comment by Shirling-VT** [comment]
Hi Evan,

You are right. We discussed all the pull requests and didn't have enough time to go through all the issues during the developer telecon.

**Comment by ksterne** [comment]
Apologies @egthomas that this was never addressed or fixed.  One of davitpy's many flaws.  Closing this issue now at the repo is being deprecated.
