### ISSUE TITLE
Infinite loop when trying to find data from the database 

### ISSUE THREAD

**Issue by mts299** [vtsuperdarn/davitpy#355]
While fixing the issue in #354, I noticed when there is no data in the database for a specific date for a given radar the script goes into an infinite loop of trying to find the data: 
`
data_date = datetime(2015,03,17,00,00)
davitpy.pydarn.plotting.fan.plotFan(date, rad=['cly','rkn'], param=param, gsct=True, show=False, png=True)
`
The following continously prints out: 
WARNING:root:cannot access [data/2014/lmfit/rkn/]

**Comment by asreimer** [comment]
Since the VT server no longer exists, we can't fix this.
