### ISSUE TITLE
Continents don't move with time in AACGM maps

### ISSUE THREAD

**Issue by johncoxon** [vtsuperdarn/davitpy#366]
I am currently experimenting with plotting AMPERE data on a `plotUtils.mapObj` and it's going pretty well, but I think I've uncovered a bug. When I plot in AACGM coordinates, the continents don't rotate underneath the data, which I think they should do – in the below code I would expect the continents to be rotated 180° from each other, and they are clearly not (see picture).
```
plt.close('all')
fig, ax = plt.subplots(2)
aacgm_map1 = plotUtils.mapObj(datetime = dt.datetime(2012,12,3), boundinglat = 60, coords = 'mag', altitude = 780, ax = ax[0])
aacgm_map2 = plotUtils.mapObj(datetime = dt.datetime(2012,12,3,12), boundinglat = 60, coords = 'mag', altitude = 780, ax = ax[1])
```
![continents-not-rotating-in-mapobj](https://user-images.githubusercontent.com/1693743/42268917-abeae208-7f74-11e8-8717-5f4241b40964.png)

**Comment by MuhammadVT** [comment]
Hi,

If you want to rotate the continents while setting coords = "mag", you can
do so by  changing lon_0 argument. If you want the map to be in coords =
"mlt", then it will rotate automatically based on the datetime you entered.

Hope this help.

Muhammad

**Comment by johncoxon** [comment]
Thanks, that was very helpful! I hadn't appreciated that longitude in AACGM is defined by where the geomagnetic pole resides, rather than by where the Sun is. I presume setting coords = MLT keep everything in AACGM but orient the continents by MLT rather than by longitude?

It might be useful to add some examples of maps using `coords= "mlt"` to the Jupyter Notebooks that demonstrate use of the `mapObj` object, so that future users don't trip up in the same way, but I will mark this ticket closed.
