### ISSUE TITLE
Error in Super Darn data plotting

### ISSUE THREAD

**Issue by snowpalace** [vtsuperdarn/davitpy#368]
I 

I got the following error while using the Superdarn data plotting code. Can I please get some help in resolving this issue. AttributeError                            Traceback (most recent call last)
<ipython-input-11-40ecc1a03393> in <module>()
      9 sdate = datetime.datetime(2011, 4, 3, 4, 0)
     10 print sdate
---> 11 mObj = plotUtils.mapObj(boundinglat=-50., datetime=sdate, gridLabels=True, coords='geo')
     12 mapDatObj = davitpy.pydarn.plotting.plotMapGrd.MapConv(sdate, mObj, ax)
     13 mapDatObj.overlayMapFitVel()

/usr/local/lib/python2.7/dist-packages/davitpy-0.8-py2.7-linux-x86_64.egg/davitpy/utils/plotUtils.pyc in __init__(self, ax, datetime, coords, projection, resolution, dateTime, lat_0, lon_0, boundinglat, width, height, draw, fillContinents, fillOceans, fillLakes, fill_alpha, coastLineWidth, coastLineColor, grid, gridLabels, gridLatRes, showCoords, altitude, lon_label_style, **kwargs)
    216 
    217         if draw:
--> 218           self.draw(lon_label_style=lon_label_style)
    219 
    220     def draw(self, lon_label_style=None):

/usr/local/lib/python2.7/dist-packages/davitpy-0.8-py2.7-linux-x86_64.egg/davitpy/utils/plotUtils.pyc in draw(self, lon_label_style)
    235         _ = self.fillcontinents(color=self._fillContinents,
    236                                 lake_color=self._fillLakes,
--> 237                                 alpha=self._fill_alpha)
    238 
    239         # Add coordinate spec

/usr/local/lib/python2.7/dist-packages/mpl_toolkits/basemap/__init__.pyc in fillcontinents(self, color, lake_color, ax, zorder, alpha)
   1765         ax = ax or self._check_ax()
   1766         # get axis background color.
-> 1767         axisbgc = ax.get_axis_bgcolor()
   1768         npoly = 0
   1769         polys = []

AttributeError: 'AxesSubplot' object has no attribute 'get_axis_bgcolor'

Any help would be great. 

Thanks,
  Shree

**Comment by ksterne** [comment]
Apologies this issue was never addressed. However, closing this issue now as this repo is being deprecated.
