### ISSUE TITLE
DavitPy was not installed succesfully

### ISSUE THREAD

**Issue by zhousujob** [vtsuperdarn/davitpy#371]
Hi everybody,

I got a problem when I tried to install Davitpy on Ubuntu 19. I run 'sudo python setup.py install', and then I saw this problem:

zhousu@zhousu-virtual-machine:~/davitpy$ sudo python setup.py install
[sudo] password for zhousu: 
make: Entering directory '/home/zhousu/davitpy/davitpy/models/raydarn'
mpif90 -w -g -O2 -fbacktrace -fno-automatic -c ../iri/irifun.for -o ../iri/irifun.o
../iri/irifun.for:4540:21:

       CALL SPHARM_IK(C,6,6,RCOLAT,RMLT)
                     1
Error: Actual argument contains too few elements for dummy argument ???c??? (49/82) at (1)
../iri/irifun.for:4715:21:

       CALL SPHARM_IK(C,6,6,RCOLAT,RMLT)
                     1
Error: Actual argument contains too few elements for dummy argument ???c??? (49/82) at (1)

Does anybody knows how to solve this problem?

**Comment by asreimer** [comment]
Hi @zhousujob, what operating system are you running on and what is your version of gcc? This looks to me like you have gcc 8, which is much more strict about Fortran syntax.

**Comment by zhousujob** [comment]
Hi @asreimer , my operrating system is Ubuntu 19,  gcc is 8. Which version should I use? Thanks.

**Comment by asreimer** [comment]
Hi @zhousujob, do not try to install a different gcc version, that shouldn't be necessary. Instead you can add the `-std=legacy` flag to [this line of the raydarn makefile](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/models/raydarn/Makefile#L9).

You will probably need to add that flag in other places to get the other models to compile as well. The other models are compiled with f2py, so you need to pass the option as a compiler flag using an environment variable. Something like this should work:

    FFLAGS='--std=legacy'  python setup.py install --user

You also should not need to use sudo. Use the --user flag instead.

**Comment by mts299** [comment]
Hi @zhousojob, 

What are you wanting to use DaViTpy for? 

If you want to read in damp (superDARN files) there is another library currently in development that might be easier to install. https://GitHub.com/superDARN/pydarn 

DaViTpy is becoming deprecated and being replaced by pyDARN which uses python 3.5

**Comment by zhousujob** [comment]
> Hi @zhousujob, do not try to install a different gcc version, that shouldn't be necessary. Instead you can add the `-std=legacy` flag to [this line of the raydarn makefile](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/models/raydarn/Makefile#L9).
> 
> You will probably need to add that flag in other places to get the other models to compile as well. The other models are compiled with f2py, so you need to pass the option as a compiler flag using an environment variable. Something like this should work:
> 
> ```
> FFLAGS='--std=legacy'  python setup.py install --user
> ```
> 
> You also should not need to use sudo. Use the --user flag instead.

Hi，thanks very much for your nice reply.
I will try to install DavitPy again. I have another question.  Is DaviTPy supported by Python 3.5?

Good luck. Have a nice weekend.

**Comment by zhousujob** [comment]
> Hi @zhousojob,
> 
> What are you wanting to use DaViTpy for?
> 
> If you want to read in damp (superDARN files) there is another library currently in development that might be easier to install. https://GitHub.com/superDARN/pydarn
> 
> DaViTpy is becoming deprecated and being replaced by pyDARN which uses python 3.5

Hi, I just want to obtain superDarn convection map to investigate some questions involved in auroral phenomena. I need mainly two types data: convection velocity along the line of sight of a single radar, and a global convection map (i.e. fitting convection velocities of all radars).
Indeed, I feel that DavitPy is very hard to be installed. This module often has some bugs.

I will try to install pyDARN. Thanks for your good suggestion.

**Comment by aburrell** [comment]
> I have another question. Is DaviTPy supported by Python 3.5?

No, DaViTPy is only supported by python2.  Support for this community-driven module has been directed towards pyDARN after deciding that a scope overhaul was needed to improve maintainability.  If you want to use python 3, pyDARN can certainly allow you to look at the line-of-sight Doppler velocity from a single radar.  @mts299 does dmap allow one to read the map files?

**Comment by asreimer** [comment]
@aburrell @zhousujob yes, pydarn can read map files.
