### ISSUE TITLE
Dealing with rtypes.h (edit: replacing dmap.c with python code)

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#45]
Posting this so we remember to address it at a later date. As @jspaleta said we need to work towards replacing rtypes.h with "calls to types defined in stdint.h" see https://github.com/vtsuperdarn/davitpy/pull/44

And see https://github.com/vtsuperdarn/davitpy/pull/44#issuecomment-49827658

**Comment by asreimer** [comment]
Looking at this again, it might be easiest if we completely replace the `dmap.c` code with a python version instead.

**Comment by asreimer** [comment]
Our software engineer here in Saskatchewan has a working python version of the dmap library.

I'll see if I can use it here. If so, we have a python version of dmap.

**Comment by ksterne** [comment]
@asreimer. @kkotyk, just to highlight how long and how many "issues" could be cleared out.  Seems as though this one is pending the python dmap library as well...

**Comment by asreimer** [comment]
This is now achieved with #249.
